### ISSUE TITLE
Demo Proposal: Bring your own signals

### ISSUE THREAD

**Issue by izimuth** [VanJS/meetup#100]
- **Draft Title:** Bring your own signals - reactivity is easier than you think
- **Length:** 5-10min

A brief talk highlighting how you can write your own signals library and how reactivity works in JavaScript.

### Speaker Bio (optional)
- **Name:** Ian
- **Mini-bio:** 17 YoE full stack developer 
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?** Yes

**Comment by bibschan** [comment]
Hey @izimuth ! We have a full lineup in July and August, do you think September/October would work for you? On another note, is this your first time giving a public presentation?

**Comment by bibschan** [comment]
hey @izimuth I have one spot open for our July 24th event, any chance you'd like to take it? let me know!

**Comment by izimuth** [comment]
Hi Bibi

Yes I should be able to make it out for then!

Thanks!
Ian

**Comment by bibschan** [comment]
ok perfect, please secure your ticket using code SPEAKER here https://lu.ma/kb271tfh

**Comment by izimuth** [comment]
Hey its saying the coupon code is expired or invalid

**Comment by bibschan** [comment]
> Hey its saying the coupon code is expired or invalid

could you please try one more time? I had to update something in the dashboard for it to work.... thank you!

**Comment by bibschan** [comment]
hey @izimuth, let me know if you could send me a picture of yourself for my slides and your linkedin profile so I can tag you on my posts!

**Comment by bibschan** [comment]
hey @izimuth just following up here on my last message!

**Comment by izimuth** [comment]
Ah! sorry i keep forgetting to get back to you - https://www.linkedin.com/in/ian-smith-3177b0295/ here is my linked in; my profile pic is the "best" picture that i can give you right now in that its the only picture that i have available

**Comment by bibschan** [comment]
hey @izimuth let me know how you'd like me to introduce you to the crowd before your presentation, currently your mini-bio is `17 YoE full stack developer` and I could use that, but lmk if you prefer anything else!
