### ISSUE TITLE
Talk Proposal: Information vs Experience: how to build mature Design Systems

### ISSUE THREAD

**Issue by gustavoteodoro** [VanJS/meetup#101]
- **Draft Title:** Information vs Experience: how to build mature Design Systems
- **Length:** 20 min
- **Links:** [Original Article](https://uxdesign.cc/how-the-distinction-between-information-and-experience-can-contribute-to-the-maturity-of-a-design-1f85d03dced8) 
- **Which dates, particularly Tue/Wed/Thu during the 2nd/3rd week of a month, are you likely available?** Most weekdays in July / August / October

Projecting and implementing a Design System can be challenging. One of the main questions is: How can we ensure that the Design System will positively impact the user experience? This talk proposes to answer this question through a reflection in dialogue with the ideas of a Doctor in Pedagogy about Information and Knowledge of Experience to achieve the next-level of maturity for Design Systems.

### Speaker Bio
- **Name:** Gustavo Teodoro
- **Mini-bio:** Staff Front-End Engineer at Thinkific. Passionate about Design Systems, User Experience and Web Accessibility.
- **Would you like help with your presentation?** yes
- **Social media link(s):** [Linkedin](https://www.linkedin.com/in/gustavoteodoro/) | [Website](https://teodoro.dev/)
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?** yes

**Comment by bibschan** [comment]
Hey @gustavoteodoro! We can slot you in for October, would that work for you? We don't have firm dates yet but usually host the event in the last week of the month. Let me know how that sounds!

**Comment by gustavoteodoro** [comment]
Hey @bibschan yes of course that works for me! Thanks a lot for accepting my proposition!

**Comment by bibschan** [comment]
hey @gustavoteodoro I just so happen to have one spot open for our July 24th event, any chance you'd like to take it? let me know!

**Comment by gustavoteodoro** [comment]
Hey @bibschan sorry... I missed the timing here. I'm glad that another speaker took the spot 😃 sorry about that!

**Comment by bibschan** [comment]
@gustavoteodoro I got a spot open for August 28th! Would you like to speak at this event?

**Comment by bibschan** [comment]
@gustavoteodoro let me know if you could send me a picture of yourself for the introduction slides!

**Comment by bibschan** [comment]
thank you for speaking at VanJS @gustavoteodoro! We would love to have you again 💛
