### ISSUE TITLE
Talk Proposal: Introduction to Immersive Experiences with WebXR

### ISSUE THREAD

**Issue by hblee12294** [VanJS/meetup#102]
- **Draft Title:** Introduction to Immersive Experiences with WebXR
- **Length:** 15~20 mins (Can be shorten to 10 mins without going through the demo if time is limited)
- **Links:** https://webxr-tutorial-next.vercel.app/
- **Which dates:** 27th July VanJS Event or Most weekdays in August

The talk will introduce the exciting world of WebXR and demonstrate how to develop a simple immersive application using WebXR, Next.js and Three.js.

### Speaker Bio
- **Name:** Hongbin Li
- **Mini-bio:** Senior Front-end Engineer at Tencent, formerly a Web 3D engineer in the autonomous driving industry. Extensive experience in designing and developing Web 3D applications and SDKs.
- **Would you like help with your presentation?** feedback on notes
- **Social media link(s):** https://www.linkedin.com/in/hongbin-li/
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?** Yes

**Comment by bibschan** [comment]
Hey @hblee12294! We have a full lineup in July and August, do you think September would work for you? On another note, is this your first time giving a public presentation?

**Comment by hblee12294** [comment]
Hi @bibschan, thank you for organizing. September most likely works for me. While I have given several tech talks within my company, this will be my first time presenting to a broader public audience.

**Comment by bibschan** [comment]
sounds great @hblee12294! I'll put you down for September and touch base with you in August :) would you be able to provide me with a picture so I can use for the slides later on? thanks!

**Comment by hblee12294** [comment]
Thank you @bibschan! May I ask what kind of picture you need? My portrait or about my topic?

**Comment by bibschan** [comment]
@hblee12294 your portrait! This is for the slides I use when introducing speakers :)

**Comment by bibschan** [comment]
hey @hblee12294 would you be available to speak this August 28th by any chance? a spot just opened up and I thought I'd check with you!

**Comment by hblee12294** [comment]
@bibschan Yes I can take that spot!

**Comment by bibschan** [comment]
ok perfect! I will announce your participation then :)

**Comment by bibschan** [comment]
perfect, please secure your ticket here using code `SPEAKER` here https://lu.ma/gykjonp2

**Comment by bibschan** [comment]
@hblee12294 would you be able to send me your headshot for our website and event slides? thanks!

**Comment by hblee12294** [comment]
> @hblee12294 would you be able to send me your headshot for our website and event slides? thanks!

Sure! I'll send it to you by email!

**Comment by bibschan** [comment]
thank you for speaking at VanJS @hblee12294!
