### ISSUE TITLE
Talk Proposal: The C4 Model, a way to explain complex software systems in a simple way

### ISSUE THREAD

**Issue by gyunayK** [VanJS/meetup#104]
- **The C4 Model, a way to explain complex software systems in a simple way** 
- **Length:** 10 - 15 mins
- **Links:** https://c4model.com/

I will discuss the C4 model, a framework for visualizing complex software systems. This model is highly beneficial for developers, providing a clear and structured way to represent various aspects of software architecture. By implementing the C4 model, developers can improve communication, enhance understanding, and ensure better alignment within their projects. I think every developer should be familiar with this model and consider integrating it into their workflows.

If it's possible I can showcase a short demo, the company I am interning at has built their tool around the c4 model. (not trying to promote, the tool has a free tier and its cool if the answer is no)  --> https://icepanel.io/

### Speaker Bio
- **Gyunay Kadirov:** 
- **Mini-bio:** 
I started my coding journey in late 2022 and have just about a year of experience in the industry. 
Currently, I am doing an internship at IcePanel. 
- **Picture for slides:** (We like to include a picture of each speaker in our slides for the event intro)
- **Would you like help with your presentation?** Yes, pls 
- **Social media link(s):** https://www.linkedin.com/in/gyunayk/
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?** YES

**Comment by bibschan** [comment]
hey @gyunayK we can put you down for october or november, would that work for you? I see you also want help with your presentation, let me know how I may assist!

**Comment by bibschan** [comment]
hey @gyunayK just wanted to follow up!

**Comment by gyunayK** [comment]
@bibschan Hey I just saw this mb

**Comment by gyunayK** [comment]
I haven't done any talks before so I will need to practice a few.

**Comment by gyunayK** [comment]
October sounds good!

**Comment by gyunayK** [comment]
I haven't done any presentations before so I want to practice a few times. Can I practice a few times a day or two before the event?

**Comment by bibschan** [comment]
hey @gyunayK, I'm just organizing the spots for October and realized I had filled those already, would November work for you as well? I don't have solid dates yet but will let you know in advance

**Comment by gyunayK** [comment]
@bibschan Yep no problem November sounds good!
