### ISSUE TITLE
Demo Proposal: Enchant your website with VFX-JS

### ISSUE THREAD

**Issue by fand** [VanJS/meetup#108]
- **Draft Title:** Enchant your website with VFX-JS
- **Length:** 5min or 10min, whichever

I'm gonna introduce VFX-JS, a library to add WebGL effects to images / videos.
I'll explain what it does, how it works, the story behind the development, and technical challenges VFX-JS does under the hood.
https://amagi.dev/vfx-js/

My demo will be short, and I'm ready to give a demo at the July event.
If it's difficult I'm also available in August or later.

### Speaker Bio (optional)
- **Name:** Amagi
- **Mini-bio:** Freelance Web Graphics Dev.
- **Would you like help with your demo?:** No
- **Social media link(s):** https://twitter.com/amagitakayosi
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?:** Yes

**Comment by bibschan** [comment]
hey @fand thanks for opening an issue with us! We are fully booked up for July and August as of now. I can put you on a waitlist in case someone drops, but otherwise I'm happy to slot you in for October if that works? let me know!

**Comment by bibschan** [comment]
hey @fand I might have a spot for you for next week's event -- I have another speaker who is not responding to my emails and I'm not sure what's going on. Would you be prepared to give your demo next week if the spot opens up? no pressure!

**Comment by fand** [comment]
@bibschan Hi! Thank you for your response.
Understood, I'm okay to be placed in October but I'll still prepare my demo in case the speaker can't present at next week's event. 🙏

**Comment by fand** [comment]
Sure👌  here's the draft of my slide.
[vfx-js-vanjs.pdf](https://github.com/user-attachments/files/16262642/vfx-js-vanjs.pdf)

> let me know how you'd like me to introduce you and the demo, if anything specific needs to be mentioned :)

Well, I don't have any idea about the introduction... how about this?
```
Amagi is a freelance web engineer from Japan. He's gonna show us his library named VFX-JS.
```

**Comment by bibschan** [comment]
perfect thanks for sharing! I heard back from our other speaker so I'll put you in for October @fand thanks again for being flexible!

**Comment by bibschan** [comment]
@fand please secure your ticket here using code `SPEAKER` here https://lu.ma/gykjonp2

**Comment by fand** [comment]
@bibschan thx, I got a ticket now 🙏

**Comment by bibschan** [comment]
@fand can you send me a headshot of yourself so I can add to our website and event slides?

**Comment by fand** [comment]
@bibschan plz use this :pray:
![SDIM3378-2](https://github.com/user-attachments/assets/98767824-17ee-4b80-934b-d4e9402419ba)

**Comment by bibschan** [comment]
thank you for speaking at VanJS @fand!
