### ISSUE TITLE
Talk Proposal: Developing an accounting application using Next.js

### ISSUE THREAD

**Issue by nobu0605** [VanJS/meetup#109]
- **Draft Title:** 
 How GreatFrontEnd is connected to our actual work
- **Length:** (5 min lightning talk, or 10-20 min full presentation)
 10 min
- **Links:** (slides, article, notes)
Slide: https://docs.google.com/presentation/d/1vIGzpCE2RKqcXQ_Z2UyQEOwIFt00kMI3LgmFU5B7fVc/edit?usp=sharing
GreatFrontEnd: https://www.greatfrontend.com/
- **Which dates, particularly Tue/Wed/Thu during the 2nd/3rd week of a month, are you likely available?** (e.g. "Most Thursdays with 4 weeks notice", "June or later", etc.)
Any time

**short summary of your talk.**
・Introduction of GreatFrontEnd
・I will explain how GreatFrontEnd is connected to our actual work from my experience as a front-end engineer for 4 years and a half.
I will show the actual questions on GreatFrontEnd and share how to solve them.

### Speaker Bio
- **Name:**  Nobu
- **Mini-bio:** (This is the introduction our emcee will give about you, one paragraph is usually best)
I have been working as a software engineer for over 6 years. I'm a freelance. I specialize more in front-end.
- **Picture for slides:** (We like to include a picture of each speaker in our slides for the event intro)
- **Would you like help with your presentation?** (Feedback on notes, practice run)
It's okay but it would be great if I could have some.
- **Social media link(s):** (twitter, website, linkedin, etc.)
twitter: https://x.com/nobubump0
linkedin: www.linkedin.com/in/takanobu-suzuki-563455147
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?**
Yes!

**Comment by bibschan** [comment]
hey @nobu0605, we can slot you in for November this year, would that work for you? :)

**Comment by nobu0605** [comment]
@bibschan 
Sure! It works for me!

**Comment by nobu0605** [comment]
@bibschan 
Would it be possible to change the topic of my talk scheduled for November?
Below is my new proposal. However, if it’s more convenient to keep the original topic, I’m happy to proceed with that as well.

**Comment by nobu0605** [comment]
- **Draft Title:** 
 Developed an accounting application using Next.js
- **Length:** (5 min lightning talk, or 10-20 min full presentation)
 10 min
- **Links:** (slides, article, notes)
Slide: https://docs.google.com/presentation/d/1E5hlDFF0M1SdXSZL4JTbxO-_FG5_nmaAKXqmjZMKXlA/edit?usp=sharing
Demo site: https://accounting-app-six.vercel.app/

**short summary of your talk.**
・I will explain how I developed an accounting application from my background in accounting for 3 and a half years.
・Demo
I will show the features and how it works.

**Comment by bibschan** [comment]
hey @nobu0605 of course you can change, no worries at all. That sounds like a great topic so I'm happy to update it!

**Comment by bibschan** [comment]
hey @nobu0605 could you share with me a picture of yourself for my intro slides?

**Comment by nobu0605** [comment]
@bibschan 
Hi! Please use this picture.
https://pbs.twimg.com/profile_images/993835438614892546/oCG687Xb_400x400.jpg

**Comment by bibschan** [comment]
thank you for speaking at VanJS @nobu0605! It was a pleasure hosting you :)
