### ISSUE TITLE
Sponsor: Atono [August 2024]

### ISSUE THREAD

**Issue by mlooooo** [VanJS/meetup#111]
## Information

Company name: Atono

Reason for sponsoring: (sales pitch? hiring? just because you love JavaScript?) sales pitch

Contact info: (email, linkedin or twitter is fine) megan.lo@atono.io

Logo: (either a link or an image that we can include in the slides)
![Atono-Logo](https://github.com/user-attachments/assets/8d023994-a3f7-4a14-93a4-84e1a7ee6853)

**Comment by bibschan** [comment]
hey @mlooooo! I just reached out over email, let me know if you received it 😃

**Comment by mlooooo** [comment]
Received! Will respond via email. Thank you @bibschan!
