### ISSUE TITLE
Talk Proposal: Lost and Found: A Decade of Modern JS and the Rise of Serverless Fullstack

### ISSUE THREAD

**Issue by brianleroux** [VanJS/meetup#112]
- **Draft Title:** Lost and Found: A Decade of Modern JS and the Rise of Serverless Fullstack
- **Length:** 20 min full presentation
- **Links:** [(slides, article, notes)](https://tinyurl.com/lostandfoundjs)
- **Which dates, particularly Tue/Wed/Thu during the 2nd/3rd week of a month, are you likely available?** Only available in October and will absolutely wear a Halloween costume 

The past decade in web development has often been characterized as a "lost decade" for modern JavaScript, marked by fragmentation and shifting paradigms. Meanwhile, serverless architectures have quietly grown more capable and influential. This talk examines the dual evolution of JavaScript frameworks and serverless technologies, highlighting the challenges and triumphs of each. We'll discuss how serverless has matured to become a cornerstone of scalable, efficient backend solutions, and how modern JavaScript has navigated its turbulent journey.

### Speaker Bio
- **Name:** Brian LeRoux
- **Mini-bio:** Old school JavaScript developer
- **Picture for slides:** ![me](https://github.com/user-attachments/assets/dc135979-2c91-40fa-8ffe-d5bffc38b3c7)
- **Social media link(s):** https://webdev.rip
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?** yes

**Comment by bibschan** [comment]
@brianleroux I just secured a venue for October 25th, would that work for you?

**Comment by brianleroux** [comment]
works for me!

**Comment by bibschan** [comment]
thank you for speaking at VanJS @brianleroux! We would love to have you again and looking forward to seeing you next month 💛
