### ISSUE TITLE
Talk Proposal: Chat-oriented programming (CHOP) in action

### ISSUE THREAD

**Issue by ykdojo** [VanJS/meetup#113]
- **Draft Title:** 
- **Length:** 10-20 min full presentation
- **Links:** Two relevant videos:
1. https://youtu.be/CZGDhgcQL6I
2. https://drive.google.com/file/d/1J1zPrdtY9IotvrqOTqPYsppRZYUxGe3H/view?usp=sharing

Many programmers know AI tools are important, but they might feel like it's all new and aren't sure how to actually use them effectively. What are the best techniques? How can they be applied to real-world projects?

This session will show you how to become proficient in AI-assisted programming, boosting your efficiency and productivity. Engineering teams can become 20-30% more productive, and individuals can see a 2-3X improvement, especially on new projects.

In this session, you'll learn:

* How to use AI chat effectively in a professional setting
* Specific techniques and examples for using AI in both new and existing projects
* How to leverage context and different input types to get the most out of AI tools

You'll come out of this talk knowing the mindset you should have to become a chat-oriented programmer, become proficient using AI technologies like ChatGPT, Claude, or Gemini, and even teach some of your teammates how to use these technologies.

### Speaker Bio
- **Name:** YK Sugi
- **Mini-bio:** Senior AI Developer Advocate at Sourcegraph. Also a creator of an open source coding assistant with 1200 stars on GitHub. Founder of CS Dojo, a programming education YouTube channel with 1.9M+ subscribers.
- **Picture for slides:** 
![IMG_2911](https://github.com/user-attachments/assets/4b15e0de-be4c-4089-85aa-7d57c2e697ea)
- **Would you like help with your presentation?** No
- **Social media link(s):** https://csdojo.io/speaking
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?** Yes

**Comment by bibschan** [comment]
thank you for opening an issue with us @ykdojo! I can schedule you for November or any month onwards, let me know if you have a preference. I don't have solid dates for November yet but we usually host VanJS either on the last Tuesday/Wednesday of the month.

**Comment by ykdojo** [comment]
Thank you @bibschan!

I may not be in town for Nov 4 - 8, but otherwise, it should work for me.

**Comment by ykdojo** [comment]
It was great giving this talk!
https://youtu.be/fYWz7pUiwls

**Comment by bibschan** [comment]
thank you for speaking at VanJS @ykdojo! It was a pleasure hosting you :)
