### ISSUE TITLE
Talk Proposal: Build AI Applications using Agents in Pure Javascript

### ISSUE THREAD

**Issue by YourTechBud** [VanJS/meetup#118]
- **Draft Title:** Build AI Applications using Agents in Pure Javascript
- **Length:** (5 min lightning talk, or 10-20 min full presentation) Full length
- **Links:** (slides, article, notes) Not yet. Will share soon.
- **Which dates, particularly Tue/Wed/Thu during the 2nd/3rd week of a month, are you likely available?** (e.g. "Most Thursdays with 4 weeks notice", "June or later", etc.) I can make time for VanJS

GenAI is here. It's happening and everyone seems to be rushing towards it. But why is the AI field dominated by Python? That's just - Ewwww. Lets learn how we can build practical and fully featured GenAI powered applications using pure JavaScript.

### Speaker Bio
- **Name:** Noorain - YourTechBud
- **Mini-bio:** (This is the introduction our emcee will give about you, one paragraph is usually best) anything is fine. Just don't call me a comedian. Lol. Who am I kidding. Noorain a.k.a. YourTechBud is a comedian disguised as a techie. He has a bitter-sweet relationship with JavaScript so let's hope we can get him to the other side.
- **Picture for slides:** (We like to include a picture of each speaker in our slides for the event intro)
- **Would you like help with your presentation?** (Feedback on notes, practice run)
- **Social media link(s):** (twitter, website, linkedin, etc.) [LinkedIn](https://www.linkedin.com/in/noorain-panjwani/)
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?** Yup

**Comment by bibschan** [comment]
thank you for speaking at VanJS @YourTechBud! It was a pleasure hosting you :)
