### ISSUE TITLE
Talk Proposal: Create a CUSTOM Full Stack App in 5 minutes with AI

### ISSUE THREAD

**Issue by bstn-aug-2024** [VanJS/meetup#120]
- **Draft Title:*Create a CUSTOM Full Stack App in 5 minutes with AI**
- **Length:** 15-20 minute presentation with demo
- **Links:** N/A
- **Which dates, particularly Tue/Wed/Thu during the 2nd/3rd week of a month, are you likely available?** Oct, Nov, Dec, Jan

We are going to look into Marblism, an AI tool that lets developers create a Full Stack App with the use of prompts. During the demo we will create a Full Stack app within minutes, taking the idea of the app from the audience and showing the true power of AI and how it is going to transform the future of Web/App Development

### Speaker Bio
- **Name:*Umer Khalid* 
- **Mini-bio:** AI Enthusiast with 8 years of experience in Full Stack Development
- **Picture for slides:** (We like to include a picture of each speaker in our slides for the event intro)
- **Would you like help with your presentation?** (Feedback on notes, practice run): No
- **Social media link(s):** (twitter, website, linkedin, etc.): https://www.linkedin.com/in/umerkhalid1/
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?*Yes*

**Comment by bibschan** [comment]
hey @bstn-aug-2024 great to see your proposal, I love the topic and seems quite relevant! We're packed full until January, would you be interested in speaking then?
