### ISSUE TITLE
Sponsor: Atono [October 2024]

### ISSUE THREAD

**Issue by mlooooo** [VanJS/meetup#123]
## Information

Company name: Atono

Reason for sponsoring: (sales pitch? hiring? just because you love JavaScript?) to collect beta testers

Contact info: (email, linkedin or twitter is fine) megan.lo@atono.io

Logo: (either a link or an image that we can include in the slides)
![Atono Stack Mixed](https://github.com/user-attachments/assets/49c1f0a8-d0e0-4016-acad-ced88e7aa64e)

**Comment by bibschan** [comment]
thank you for opening a sponsorship request with us again @mlooooo, so happy to have you again!

**Comment by bibschan** [comment]
thank you @mlooooo for the continuous support <3
