### ISSUE TITLE
Talk Idea: Node project best practises

### ISSUE THREAD

**Issue by daffl** [VanJS/meetup#18]
- **Draft Title:** Node project best practises
- **Length:** 35 minutes
- **Links:** This talk would be a shorter summary of the three workshops we are currently working on for Nodeschool (/cc @keywordnew, @Qard). First workshop slides at https://cambiecollective.github.io/open-source-start/

With all the tools and modules available, setting up a new NodeJS project can be a little overwhelming. 
In this talk I'd like to go over some tools and best practises that can make creating and maintaining a NodeJS project easier without getting in the way:

- NodeJS application vs module
- Project structure
- Testing and code coverage
- Continuous integration
- Publishing and maintenance

### About Me
- **Name:** David Luecke
- **Mini-bio:** Open sourcerer @feathersjs, decentralizer @bidalihq, rock-climber, synthesizerer, Vancouverite, German
- **Would you like help with your presentation?** Will let you know
- **Social media link(s):**  @daffl on GitHub and Twitter
- **Do you agree to the [VanJS Code of Conduct](https://github.com/cambiecollective/vanjs/blob/master/CONDUCT.md)?** Yes 👍

**Comment by ShMcK** [comment]
Closing as stale. But feel free to re-open if you're looking to give a talk in 2023!
