### ISSUE TITLE
Talk Idea: Lodash

### ISSUE THREAD

**Issue by james2doyle** [VanJS/meetup#19]
- **Draft Title:** Lodashing around
- **Length:** 20-45 min full presentation
- **Links:** No links, but I have been developing a little course on the topic of lodash and some of the more obscure and slick things you can do

This presentation will showcase the [lodash library](https://lodash.com/docs/4.17.11). Lodash is a popular tool for dealing with collections of objects and arrays. It also includes little helpers for other things (templates, conditional checks, string helpers, etc.) that can be used to create some very terse solutions to common problems. This talk will go over some common patterns you may encounter and how to use lodash to solve them.

### About Me
- Name: James Doyle
- Mini-bio: Full-stack developer. Works at Sycle, upgrading the frontend of the application to React
- Would you like help with your presentation? I'm OK
- Social media link(s) (twitter, website, linkedin, etc.): @james2doyle everywhere
- Do you agree to the [VanJS Code of Conduct](https://github.com/cambiecollective/vanjs/blob/master/SPEAKING.md)? Yes

**Comment by ShMcK** [comment]
Sounds super helpful. Maybe even some "lodash refactor challenges" for the audience. 

Which dates might you be available?

**Comment by james2doyle** [comment]
Yeah that would be fun. Maybe turn it into more like a gameshow with questions and answers haha

I'm pretty open as long as I get a few weeks notice

**Comment by ShMcK** [comment]
We still need a speaker for the 28th this month. This is mostly my fault for not paying much attention to posts over the past weeks.

I thought we might try for a different speaker next month, as you had just rocked it last month. However, if we don't find someone in the next day or so, would you be willing to sign on for March 28th?

**Comment by james2doyle** [comment]
Yeah I could do that. If you do find some different speakers for this month you can bump me to next one. I'm fine with that

**Comment by keywordnew** [comment]
@james2doyle that's super supportive! 💯🙌🏽💯

**Comment by james2doyle** [comment]
Just realized the PHP meetup is on the same day (28th) so I actually CAN'T do it this month...

**Comment by james2doyle** [comment]
I'm good to go this month if that is still an option. I am also open to being bumped again in case someone else pops up. You can consider me "on call" for now.

**Comment by ShMcK** [comment]
Sounds good, I'll get the ball rolling on sorting out a venue and let you know.

**Comment by james2doyle** [comment]
If we host @enginedigital in November, I can do this talk

**Comment by ShMcK** [comment]
It's a possibility. Nothing booked yet. 

Do you have details on the @enginedigitial space? https://github.com/VanJS/meetup/blob/master/.github/ISSUE_TEMPLATE/venue-host.md

**Comment by jagonalez** [comment]
@james2doyle reached out in the survey offering to host - i can add an issue with the info

**Comment by ShMcK** [comment]
Closing as stale. But feel free to re-open if you're looking to give a talk in 2023!
