### ISSUE TITLE
Talk Idea: Creating a shared component Library

### ISSUE THREAD

**Issue by skysteve** [VanJS/meetup#23]
- **Draft Title:** Creating a shared component Library
- **Length:** 30m Presentation
- **Links:** TBD - just a proposal at the moment

Have you ever found yourself duplicating UI components across projects? Do you want to reduce your duplicated workload but don’t know where to start?

In this talk we’ll discuss how you can build your own component library for your team(s) to use across any number of your projects. Whatever framework you use, React, Vue, Polymer or even vanilla Web Components; it’s possible to create a library of common components. We’ll talk about the benefits of creating a component library along with the practical implementation. From build tools to best practices to some lessons learned the hard way!

### About Me
- **Name:** Steve Jenkins
- **Mini-bio:** Software engineer at Jungle Scout specializing in frontend. JavaScript Developer since 2012
- **Would you like help with your presentation?** Feedback would be more than welcome :)
- **Social media link(s):** [http://skysteve.com](http://skysteve.com)
- **Do you agree to the [VanJS Code of Conduct](https://github.com/cambiecollective/vanjs/blob/master/CONDUCT.md)?** Yes

**Comment by ShMcK** [comment]
Hi Steve, great topic!

Would you be available in September to give a talk?

**Comment by ShMcK** [comment]
@skysteve would you be available for Sept 11th?

**Comment by ShMcK** [comment]
Closing as stale. But feel free to re-open if you're looking to give a talk in 2023!
