### ISSUE TITLE
Move VanJS to github.com/vanjs/meetup

### ISSUE THREAD

**Issue by ShMcK** [VanJS/meetup#26]
I recently acquired "github.com/vanjs" from its previous owner.

I propose we transfer ownership of this repo to the VanJS organization. I believe it's easier to find/remember `github.com/vanjs/meetup`, and may lead to more traffic. It may even drive organic traffic.

The idea would be to eventually host a vanjs.github.io website that explains how to apply as a speaker and more info about the org. Other repos could contain presentation notes, slides, etc -similar to how things are managed for http://github.com/seattlejs. We could grant multiple admins access for those interested.

**Comment by ShMcK** [comment]
Any objections/questions/comments?

**Comment by apike** [comment]
I've appreciated the help that Cambie Collective folks have provided VanJS so far, though of course there's no reason that would need to stop if VanJS would benefit from moving repos. I'm on board with this if @ShMcK thinks this will help visibility and/or clarity for attendees.

**Comment by Qard** [comment]
No objection from me. Seems reasonable.

I only created cambiecollective in the first place to be a _support_ organization and not an umbrella organization that would _own_ the events. Having the repo here may have been convenient to get started, but may also suggest a hierarchical relation which was never intended. I think we could consider events with repos within the cambiecollective org to be in an "incubation" phase where we're trying to build them up to a point where they can be independent.

When a group moves into their own org we can still provide some support, but we should consider what the implications are for things like moderation and code of conduct enforcement. The _intent_ was for cambiecollective to be able to unify that sort of thing, to some extent.

**Comment by ShMcK** [comment]
Thanks everybody, I'll move it over and start to rally up some speakers at the new url.
