### ISSUE TITLE
Event: Hacktoberfest (Oct. 20th)

### ISSUE THREAD

**Issue by jagonalez** [VanJS/meetup#29]
October is Hacktoberfest, let's create an event around open source. 

Typical events:
- Workshop
- Hack
- Talk style (contributing, demoing open source projects)

You can check out Hacktoberfest here: https://hacktoberfest.digitalocean.com

**Comment by Qard** [comment]
I'd like to volunteer for NodeSchool to collaborate. We've been running an open source day every month for about a year alongside the core Node.js and JavaScript learning event.

@keywordnew @daffl would likely be interested too. :)

**Comment by daffl** [comment]
Was thinking the same thing when I signed up for Hacktoberfest the other day. It can also be added to the event list at https://hacktoberfest.digitalocean.com/events via https://hacktoberfest.digitalocean.com/eventkit/#form

**Comment by ShMcK** [comment]
We could try a Q&A format with active open source peeps from the community.

So far:
- @daffl (Feathers.js)
- @brentvatne (Expo)
mentioned they would be down.

Looking for one more. Any suggestions?
Also, we'd need some good Qs.

**Comment by Qard** [comment]
I'm down for representing Node.js core and/or the Elastic APM Node.js agent.

**Comment by ShMcK** [comment]
Based on the https://hacktoberfest.digitalocean.com/eventkit

Agenda Outline:
- Intro to Open Source
- Q&A (need enough mics)
- Workshop
- Hack Time + Demos

Think we just need a location and date then. 
Any limitations on date? Ideally earlier in October (2nd week?) if we're going to be in time for Hacktoberfest.

From the survey people like a Wed/Thu 6/6:30pm start.

Maybe aim for a location with lots of desks, more open space (ie. a bootcamp).

**Comment by ShMcK** [comment]
CodeCore has moved to New West.
We can get a big space (10-120) at DevHub if we do the event on a Sunday. 
BrainStation has space for 80 for a weekday.

@daffl @brentvatne @Qard thoughts?

**Comment by Qard** [comment]
I'm good with Sunday. Weekdays could be okay, though NodeSchool has generally gone for weekends so we can get a longer stretch of time to work with. If we want to fit enough time in for that whole agenda, I'd recommend trying to get a whole day to work with. Like a one-day mini conference of sorts.

Does DevHub have any restrictions on length?

**Comment by brentvatne** [comment]
sunday would work but i won't be able to attend until early afternoon. weeknights except tuesday are also good.

**Comment by daffl** [comment]
Sundays work, weekdays depend on the day.

**Comment by ShMcK** [comment]
I've emailed a few people at DevHub regarding their availability on Oct 13th (with Oct 7th, 20th as other options), hope to get on a call with them soon.  Thanks @jensen for putting me in touch.

@brentvatne when do you consider "early afternoon"? We could always move the workshop earlier to buy an extra hour.

Thanks again guys for being amazing ambassadors for the open-source community.

**Comment by ShMcK** [comment]
Does Sunday, Oct 20th work for you guys? 1-5pm? No requirement to stay for the whole period.

October 13th looks like Thanksgiving Sunday (for Canadians), so that's not the best choice. 7th is too soon.

DevHub has capacity for ~100ish with desks for 90 split across two rooms (60 & 30). The bigger room can be augmented to hold more for a speaker session. They also have audio/video equipment to fit our needs, and a stage with stools setup for this kind of talk.

**Comment by Qard** [comment]
Works for me. 👍

**Comment by Qard** [comment]
@halkeye just making sure you've seen this too.

**Comment by brentvatne** [comment]
that works for me too. early afternoon for me just means enough time to fit in a long run in the morning, so 1pm is fine.

**Comment by keywordnew** [comment]
@Qard @daffl what do you think of merging the 19th's regularly scheduled Getting Started in Open Source into this proposed event on the 20th? Could get one weekend day back ;-)

**Comment by daffl** [comment]
Yes, that totally makes sense.

**Comment by Qard** [comment]
That was my thinking as well. 👍

**Comment by ShMcK** [comment]
Still awaiting confirmation for the venue from DevHub, then I'll post it on meetup.

**Comment by keywordnew** [comment]
Thanks. I'll update the existing meetup event to point to the new event
when posted.

**Comment by ShMcK** [comment]
Confirmed, will post soon. We may need a sponsor or two for minor costs.

**Comment by Qard** [comment]
Once we've got something up on meetup I can tweet about it on the NodeSchool Twitter account. :)

**Comment by ShMcK** [comment]
Posted: https://www.meetup.com/vancouver-javascript-developers/events/265388140

Let me know if any edits are in order

**Comment by halkeye** [comment]
Your welcome to add myself. I'm strong JavaScript developer, help run node school, and involved with hacktoberfest for Jenkins.

**Comment by keywordnew** [comment]
As this is a collaboration, I'd suggest making a duplicate event in NodeSchool to share with folks, including similar details to the event posted in VanJS.

**Comment by halkeye** [comment]
> As this is a collaboration, I'd suggest making a duplicate event in NodeSchool to share with folks, including similar details to the event posted in VanJS.

who are you suggesting it to?

If you do make a nodeschool event, make sure the attendees list is 0 so people only sign up in one place

**Comment by keywordnew** [comment]
The body mentions it's a collab with VanJS. It's in draft form, to be reviewed. Y'all should have access.

https://www.meetup.com/nodeschool-vancouver/events/265445365/

It's not possible to make an attendee list with zero. It can be 1.

**Comment by halkeye** [comment]
Lgtm

**Comment by keywordnew** [comment]
Announced.

**Comment by ShMcK** [comment]
We'll need some volunteers to help setup at DevHub (12pm on Sunday, event starts at 1pm). Give a thumbs up if you'd be interested.

**Comment by ShMcK** [comment]
I put together some rough questions for the panel. Feel free to propose edits/additions/subtractions.

```
# Open Source Q & A

INTRO 

Where do you work, what does your company do, how are you involved in open source?

How did you get started in open source?

Why is open source important?

What factors do you consider when choosing between open source libraries or developing something yourself?


BUILDING A COMMUNITY

How have you gone about building an open-source community?

How do you maintain a shared vision for the project with so many contributors and collaborators?

How do you manage issues? Do you recommend any best practices for people submitting issues?

How do you project manage with various collaborators with different levels of commitment? Meetings? Tasks?

What has been your proudest moment in open source?

What has been your worst moment in open source?

Advice for people entering open source?

Have you ever had a problem with malicious members in your community trying to hijack your code?

How do you maintain coding standards in an open-source library?

What open source project do you think is crushing it? What can we learn from them?

PHILOSOPHY OF OSS

Finish this sentence: open source is like ____.

Generally - who has better code quality? Proprietary software or open source?

Why don’t we see more projects forking and splitting?

How would a world without open source be different?

LICENSES

Can you talk a bit about licensing in open source?

Lately, we’ve seen a lot of big companies like Amazon, Google & Microsoft wrapping up open source as a product and selling it. Any opinions on big companies piggybacking on open source projects?
- Ask Stephen to talk about Elastic Search & Amazon
- 
- This year, a lot of companies have changed their software licenses to more restrictive terms. Redis Labs, MongoDB, Confluent. Often in response to big companies copying and rebranding their service.
- 
What do you think when people say open source is “free”?

How does open source pay your salary?

What can we do to get more funding into open source?

AUDIENCE Q & A
```

**Comment by jensen** [comment]
Thank you to everyone for the work you put into this. Great sessions. I saw a lot of engaged people.
