### ISSUE TITLE
Talk Proposal: Make your applications faster by using AWS JavaScript SDK v3

### ISSUE THREAD

**Issue by trivikr** [VanJS/meetup#30]
- **Draft Title:** Make your applications faster by using AWS JavaScript SDK v3
- **Length:** 30 minutes full presentation
- **Links:**
  - Slides: https://slides.com/trivikram/modularized-aws-js-sdk
  - Dev-preview announcement blog post: https://aws.amazon.com/blogs/developer/new-aws-sdk-for-javascript-developer-preview/
  - Video recording from BellevueJS presentation: https://www.youtube.com/watch?v=vUom1y0tNqo
- **Which dates, particularly Tue/Wed/Thu during the 2nd/3rd week of a month, are you likely available?** Third week of January, both Wednesday/Thursday would work.

The AWS SDK for JavaScript enables developers to build libraries an applications that use AWS services. You can use the JavaScript API in the browser and inside Node.js applications on the server. The v3 is now modular and has been written in TypeScript. In this talk, we'll understand how to make your application faster by using this modularized version of AWS JavaScript SDK

### Speaker Bio
- **Name:** Trivikram Kamat
- **Mini-bio:** Trivikram is a Software Development Engineer with AWS, and maintains [AWS SDK for JavaScript](https://docs.aws.amazon.com/sdk-for-javascript/index.html)
- **Would you like help with your presentation?** It's not required, as I've given this talk in BellevueJS already. But I can work with VanJS if you want to go through the draft.
- **Social media link(s):**
  - [Twitter](https://twitter.com/trivikram)
  - [Github](https://github.com/trivikr)
  - [Website](http://trivikr.github.io)
- **Do you agree to the [VanJS Code of Conduct](https://github.com/cambiecollective/vanjs/blob/master/CONDUCT.md)?** Yes

**Comment by trivikr** [comment]
Any update on this proposal?

**Comment by ShMcK** [comment]
Looks great, could we book you for January? We can aim for Jan 15th or 16th?

**Comment by trivikr** [comment]
Jan 15th/16th might work for us. I'll just check with my team.
Is there an option to give the talk remotely or we have to be in Vancouver in-person?

**Comment by ShMcK** [comment]
We've never had a remote talk, but I think it's a good fallback plan. I wouldn't be opposed to the idea.

**Comment by trivikr** [comment]
Thanks @ShMcK for the response.

We'll give the talk in person in Vancouver BC. However, we've the following requests:
* The speaker would be Chase Coalwell (@srchase) who also contributes to AWS SDK for JavaScript
* We're interested for the dates in February. Is Thursday Feb 13th possible?

Does this work?

**Comment by ShMcK** [comment]
I think we can make that happen. I'll tag the talk with Feb 13th and look for a second speaker.

**Comment by trivikr** [comment]
Sounds good! 👍

**Comment by brentvatne** [comment]
maybe an AWS double header with @undefobj would be good? ;)

**Comment by trivikr** [comment]
@ShMcK How many attendees can we expect for this meetup?

**Comment by ShMcK** [comment]
I'd guess around 100. 

I'll book a venue this month and post.

**Comment by ShMcK** [comment]
I've confirmed a venue/sponsor for Feb 13th at BrainStation (455 Granville St #400). Does that work for you?

**Comment by trivikr** [comment]
Hi @ShMcK, we won't be able to prioritize this talk in February because of some high priority deliverables. That's why I've to close this issue.

I'll create a new issue for future meetup events, or reopen this one if our priorities change and if the speaking slot is still available for February.

**Comment by ShMcK** [comment]
Thats too bad. Thanks @trivikr
