### ISSUE TITLE
Event: Christmas Meetup of Meetups

### ISSUE THREAD

**Issue by AkimaLunar** [VanJS/meetup#31]
React Vancouver (Ria, Nick & Anita) and GDG Vancouver (Davie & Kyle) have started planning the _Christmas Meetup of Meetups_ Would be really great if Van.js could join! 🎉

## [Event] Christmas Meetup of Meetups
**When:** Second week of December

**What:** 4-5 different meetups. Each meetup brings a speaker to give a talk on a high level topic like _“What technology might be interesting to members of other meetups?”_ +Social activities, games and fun.

**Where:** TBD

**Comment by ShMcK** [comment]
I talked to Kyle, he said they're still in the planning stage at the moment, but will loop us in.
