### ISSUE TITLE
Talk Proposal: How much do you need to know about machine-learning? 

### ISSUE THREAD

**Issue by diberry** [VanJS/meetup#32]
- **Draft Title**: How much do you need to know about machine-learning?

- **Length**: 

20 (light) or 45 minutes (deep including code)

- **Links:** (slides, article, notes)
- **Which dates, particularly Tue/Wed/Thu during the 2nd/3rd week of a month, are you likely available?** 

Available on Weds

### Speaker Bio
- **Name:** 

Dina Berry

- **Mini-bio:** 

Content developer for Microsoft working on Cognitive Services. Full-stack dev in JS/TS. 

- **Would you like help with your presentation?** (feedback on notes, practice run) 

Yes, absolutely

- **Social media link(s):** 

Twitter - @dfberry
Instagram - @dfberry_
Github - @dfberry, @diberry

- **Do you agree to the [VanJS Code of Conduct](https://github.com/cambiecollective/vanjs/blob/master/CONDUCT.md)?**

Yes.

**Comment by ShMcK** [comment]
Fascinating topic, I'd love to learn more. Let me know if you have an outline, or would like to chat about it to determine the length.

**Comment by diberry** [comment]
@ShMcK My deck isn't quite ready - I'm presenting it privately to a small group in November. I'll get feedback so perhaps January is a better fit.

**Comment by ShMcK** [comment]
Great, I'll just tag this one as January for now.

**Comment by ShMcK** [comment]
I've confirmed venue/sponsor for Jan 15th at Terminal.io downtown. @diberry does that date still work for you?

**Comment by diberry** [comment]
@ShMcK Wednesday, Jan 15th works. What was the time?

**Comment by ShMcK** [comment]
It would 6pm, talks starting a little after 6:30pm. There's an option to go first or second.

**Comment by diberry** [comment]
First or second is fine. Did we settle on 20 or 45 minutes? Either works but I want to know how much to prepare.

**Comment by ShMcK** [comment]
If you're comfortable with that, take up to 45 minutes :)

**Comment by ShMcK** [comment]
Let me know if there's anything you'd like me to change: https://www.meetup.com/vancouver-javascript-developers/events/267287320/

**Comment by dfberry** [comment]
Hi Shawn,

I've tweeked my deck. Can you look it over and see what needs to be changed for your audience? Or what questions you would want answered but it doesn't answer?

Thanks,
Dina

________________________________

**Comment by diberry** [comment]
[Presentation as PDF](https://microsoft-my.sharepoint.com/:b:/p/diberry/EVRiomWs80JEkzdLI72x4rEBLnSzwEB6F6-qESaMmru_4A?e=c9S4KH)

**Comment by ShMcK** [comment]
@diberry - I'd love to take a look, but I don't seem to have access to view the presentation at microsoft-my.sharepoint.com. Is there another means, eg. OneDrive?

**Comment by ShMcK** [comment]
Thank you coming up and delivering a great talk @diberry!

**Comment by diberry** [comment]
@ShMcK It was alot of fun. You have a great group.
