### ISSUE TITLE
Q&A: Questions for Hacktoberfest Panel

### ISSUE THREAD

**Issue by ShMcK** [VanJS/meetup#36]
Post your questions for the Q & A Panel here, and we'll try to get to them in the discussion.

**Comment by himynameisdave** [comment]
First off thank you for coming out today and taking questions!

My question is about time management: how do you find the spare time to contribute to open-source, especially if you already have a full-time job?

**Comment by Sannylai** [comment]
Vagrant & .Net core are MIT license  // OPen Source Software ??

**Comment by microsoftly** [comment]
What did you do to help increase the user base/promote your open source package(s)?

**Comment by Cantor7** [comment]
Im 100% new to coding and computer programming. What is the best route for someone like me to get into coding and open-source? Where do I start?

**Comment by microsoftly** [comment]
How do you vet dependencies that you add to your projects?

(Context: avoiding issues like the event stream vuln)

**Comment by severest** [comment]
Aside from the coding, what are some of the realities of owning/contributing to open-source projects that people just getting into it might not know about?

**Comment by jrhender** [comment]
If there is an open-source project that you want to contribute to, what would you recommend to determine the specific areas or issues that you can best help out with?

**Comment by jagonalez** [comment]
Can you share any tools or resources that are available to open source projects? Similar to how Jetbrains offers free subscription to open source projects.

**Comment by ShMcK** [comment]
What makes a good issue? Do you have any good stories about "BAD" issues?
