### ISSUE TITLE
Talk Proposal: Javascript in the development of CodeCast

### ISSUE THREAD

**Issue by tkbeili** [VanJS/meetup#37]
- **Draft Title:** Javascript in the development of CodeCast
- **Length:** 20-45 minutes presentation 
- **Links:** Will come later
- **Which dates, particularly Tue/Wed/Thu during the 2nd/3rd week of a month, are you likely available?**  2nd or 3rd week of November is good with us

Talk Summary:
- CodeCast overall architecture
- Using Electron.js with React/Redux for the desktop application (CodeCast Studio)
- Using React/Redux for the player (SPA part of CodeCast)
- The reasoning for choosing Elixir on the backend (instead of JS)
- The reasoning for choosing Go for the file watcher (instead of JS)

### Speakers Bio
Speaker 1:
- **Name:**  Tammam Kbeili
- **Mini-bio:** Founder & CEO at CodeCast / Founder & Lead instructor at CodeCore
- **Would you like help with your presentation?** Yes (ideally review/opinion before talk)
- **Social media link(s):** [@tammam](http://twitter.com/tammam) on Twitter / [https://www.linkedin.com/in/tkbeili/](https://www.linkedin.com/in/tkbeili/) on LinkedIn
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?** Yes

Speaker 2:
- **Name:**  Mike Martinson
- **Mini-bio:** Polyglot developer, Cofounder/CTO @ CodeCast
- **Would you like help with your presentation?** Yes (ideally review/opinion before talk)
- **Social media link(s):** [@untimelyquests](https://twitter.com/untimelyquests) on Twitter / [https://www.linkedin.com/in/tkbeili/](https://www.linkedin.com/in/mikemartinson/) on LinkedIn
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?** Yes

**Comment by ShMcK** [comment]
Working on something similar inside of VSCode, I'll put up a proposal that would blend together topics pretty well.

**Comment by ShMcK** [comment]
Let me know about any edits/updates: 
https://www.meetup.com/vancouver-javascript-developers/events/266162173/
