### ISSUE TITLE
Talk Proposal: Exploring device detection for better user experiences in 2020

### ISSUE THREAD

**Issue by leonardofaria** [VanJS/meetup#41]
- **Draft Title:** Exploring device detection for better user experiences in 2020
- **Length**: 30m
- **Links:** https://leonardofaria.net/2020/01/15/exploring-device-detection-for-better-user-experiences-in-2020/
- **Which dates, particularly Tue/Wed/Thu during the 2nd/3rd week of a month, are you likely available?** Overall I can't think any preference

Would like to talk a little bit about device detection and how this can enhance user experience. I wrote a blog post about it a few days ago and my talk would be a long version of the post

### Speaker Bio
- **Name:** Leonardo Faria
- **Mini-bio:** Need to work on that :)
- **Would you like help with your presentation?** I am fine
- **Social media link(s):** (twitter, website, linkedin, etc.) https://twitter.com/leozera/ / https://www.leonardofaria.net / https://www.linkedin.com/in/leonardofariacoelho/
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?** Yes

**Comment by ShMcK** [comment]
Interesting topic! More complicated than it seems on the surface to determine a users device.

I was reading recently about the possible deprecation of `user-agent` and the possible implications of losing it. [Article](https://www.androidcentral.com/google-plans-improve-privacy-deprecating-user-agent-strings-chrome)

Would you be available for March 11th?

**Comment by leonardofaria** [comment]
Hi! March 11th would be great!

**Comment by ShMcK** [comment]
@leonardofaria Still on for March 11th?

**Comment by leonardofaria** [comment]
Hi @ShMcK, still good for March 11th.

Bio: Lead Software Developer at Thinkific, Mac collector and dog lover

**Comment by ShMcK** [comment]
@leonardofaria sorry to let you know, we will have to cancel the event tomorrow. Our hosts have decided not to host any events due to the potential spread of COVID-19. Perhaps we can reschedule in the future when there is less risk and uncertainty.

**Comment by leonardofaria** [comment]
@ShMcK Thanks for letting me know. Let's try in your next event but for now, not much to do

**Comment by ShMcK** [comment]
Closing as stale. But feel free to re-open if you're looking to give a talk in 2023!
