### ISSUE TITLE
Event: February 2020 Meetup

### ISSUE THREAD

**Issue by areisle** [VanJS/meetup#43]
- **Event Name:** Machine Learning with JS
  - **Decription:** 
After a January snowday, VanJS is back with a look at machine learning in JS!

That's right! Not a typo - not Python, not R - ML in JAVASCRIPT.

Not only does ML in JS have real world use cases, it also provides a familiar base for exploring the intersection of computer science and data science.

- [x] **Date/Time:** 2-13-2020 6-8pm
- [x] **MC host:** @ShMcK 

- [x] **Event Slides:** @ShMcK  will provide

- [x] **Speaker 1:** https://github.com/VanJS/meetup/issues/32
- [x] **Speaker 2:** https://github.com/VanJS/meetup/issues/35

- [x] **Venue:** BrainStation
  - **Logo:**
  - **Writeup:** 
BrainStation is the global leader in digital skills training and education. The main disciplines we teach are; Product, Design, Development, Marketing and Data. Our goal is to democratize digital skills and help empower 1 million people by 2025 through our state of the art campuses and online

https://brainstation.io/
- [x] **Sponsor:** realtor.com®
  - **Logo:**
  - **Writeup:**
realtor.com® is the fastest growing online real estate platform for homebuyers, sellers and renters. Our platform has over 3 million listings, 50+ million unique users every month and we have the most homes for sale nationwide than any competing real estate marketplaces.

In our meetup group we share, and also learn, about new technologies, engineering best practices, how to be a data driven company, how to scale your organization and technology, and many more topics. Come and mingle with our talented engineers, technology leaders and product leaders.

We are one of the top Tech Meetups in Vancouver, BC! Join us for good food and great presentations!

https://www.meetup.com/Realtor-com-Technology-meetup/
- [x] **Posted on Meetup**
- [x] **Announced on Meetup**

- [ ] **Waitlist Reminder Sent Out?**
- [x] **After Party Reservation**
  - **Under Name:** VanJS
  - **Location:** St. Regis
  
  - **Time:** 8:30pm
  - **Size:** 25

**Comment by ShMcK** [comment]
Host: I don't mind hosting this one.
Slides: I have these from the last event that was cancelled, I'll update them for this event.
Realtor Logo: 

Reatlor.com suggested we use this logo: ![realtor_dot_com_logo_icon](https://user-images.githubusercontent.com/4660659/73597794-eac17280-44e4-11ea-8823-b1dd2d41b9f5.png)

**Comment by areisle** [comment]
so we still need a logo from brainstation and then we're basically set?

**Comment by ShMcK** [comment]
Basically just for the slides. 

They have downloadable branding assets on their site: https://brainstation.io/press. Under logos. 

All good!
