### ISSUE TITLE
Event: March 2020 Meetup

### ISSUE THREAD

**Issue by areisle** [VanJS/meetup#44]
- **Event Name:** March Meetup
  - **Decription:**

- [x] **Date/Time:** 11-03-2020 6-8pm
- [ ] **MC host:**

- [ ] **Event Slides:**

- [x] **Speaker 1:** https://github.com/VanJS/meetup/issues/41
- [x] **Speaker 2:** https://github.com/VanJS/meetup/issues/46

- [x] **Venue:** TTT
  - **Logo:** (see sponsor)
  - **Writeup:** (see sponsor)
  - [ ] **Site Visit (If Required)**
- [x] **Sponsor:** TTT
  - **Logo:**
  - **Writeup:**
- [x] **Posted on Meetup**
- [x] **Announced on Meetup**

- [ ] **Waitlist Reminder Sent Out?**
- [x] **After Party Reservation**
  - **Under Name:** VanJS
  - **Location:** St. Regis
  
  - **Time:** 8:30
  - **Size:** 25

**Comment by ShMcK** [comment]
Just missing a blurb from the venue/sponsor, and we should be good to post :)

**Comment by ShMcK** [comment]
Event canceled due to a loss of venue/sponsor and risk of COVID-19 spreading.
