### ISSUE TITLE
Event: April 2020 Meetup

### ISSUE THREAD

**Issue by areisle** [VanJS/meetup#45]
- **Event Name:** TBD
  - **Decription:**

- [ ] **Date/Time:** 21-04-2020
- [ ] **MC host:**

- [ ] **Event Slides:**

- [ ] **Speaker 1:** https://github.com/VanJS/meetup/issues/40
- [ ] **Speaker 2:** 

- [ ] **Venue:** Terminal (unconfirmed)
  - **Logo:**
  - **Writeup:**
  - [ ] **Site Visit (If Required)**
- [ ] **Sponsor:** Terminal  (unconfirmed)
  - **Logo:**
  - **Writeup:**
- [ ] **Posted on Meetup**
- [ ] **Announced on Meetup**

- [ ] **Waitlist Reminder Sent Out?**
- [ ] **After Party Reservation**
  - **Under Name:** VanJS
  - **Location:**
  
  - **Time:** 
  - **Size:** 25

**Comment by ShMcK** [comment]
Closing as stale.
