### ISSUE TITLE
Talk Proposal: Dart & Flutter

### ISSUE THREAD

**Issue by MarsGoatz** [VanJS/meetup#48]
- Dart & Flutter
- 45 minutes
- https://fluttervancouver.github.io/vanjs_talk/
- Tue/Wed/Thu after 5 pm

So far JS has dominated the cross platform mobile framework, specially with framework like React Native. Now enters a new player, Dart, a new programming language created by Google that is client-optimized for fast apps on any platform. In this talk we will look 

- The story behind creation of Dart/Flutter
- Architectural differences between Dart/JS and Flutter/ReactNative
- Example on how fast we can create cross platform apps
- How the cross platform apps are optimized for specific platform, e.g, material design for Android and Apple HIG for iOS
- BONUS: Create a website without writing a single line of CSS, with all pure Dart & Flutter

### Speaker Bio
- Sid M
- Software Developer for 8 years with experience at Hewlett-Packard, Aol(yes, Aol) and Amazon
- Would appreciate it but not necessary
- Our website: https://fluttervancouver.ca, Twitter Handle: **@fluttervancity**, Meetup Group: https://www.meetup.com/flutter-vancouver-group
- Yes

**Comment by areisle** [comment]
hi @MarsGoatz given you're already booked for react vancouver for April, does May 11th or 12th work for you?

**Comment by MarsGoatz** [comment]
Hello @areisle, May 11th works for me! Thank you for reaching out! :thumbsup:

**Comment by MarsGoatz** [comment]
Hey @areisle, unfortunately I won't be able to give the talk on May 11th. Really apologize for that. Does July 13th or sometime after that work?

**Comment by areisle** [comment]
@MarsGoatz no worries about May 11th. As for a later date, I'll discuss with the other organizers and get back to you

**Comment by MarsGoatz** [comment]
Thank you @areisle 👍🏾

**Comment by MarsGoatz** [comment]
Unfortunately, don't have any bandwidth for foreseeable future for the talk. Will reopen when I get the chance.

Thank you for the consideration! Really appreciate it! 👍🏾
