### ISSUE TITLE
New Hackathons for Members

### ISSUE THREAD

**Issue by cbreen872** [VanJS/meetup#49]
Hi everyone - Ria Nicola from React Vancouver suggested I post here to let you know about our latest hackathons.  It, not only, has some great prizes up for grabs, but allows you to utilize different skills from data science to machine learning and data visualization to help scientists learn more about a large kidney dataset assembled by NanoString’s GeoMx Digital Spatial Profiler:

NanoString Spatial Omics Hackathon
GOAL: Build an open source solution that can help scientists interpret data and learn new things from a large kidney dataset assembled by NanoString’s GeoMx Digital Spatial Profiler.
PRIZES: $25,000 in prizes
DEADLINE: May 3 5:00PM EDT
JOIN THE HACKATHON: https://bit.ly/NanoString21m

Here are more hackathons listed by submission deadline:
Apr 4 (Theme: Fintech, Social Good) - Build an unbiased fintech future: http://bit.ly/OpenByDefault21x
Apr 5 (Theme: ML/AI) - Azure AI Hackathon 2021: https://bit.ly/AzureAI21m
Apr 6 (Theme: Blockchain, Fintech) - EOSIO Hackathon: Beyond Blockchain: https://bit.ly/EOSIObb21m
May 3 (Theme: Productivity) - monday apps challenge: http://bit.ly/MondayApps21q1x

Please let me know if you have any questions or if there is a better way for me to reach out.  I am more than happy to contact you another way, but as I mentioned, this is what Ria recommended.

Thanks,

Cassie @ Devpost
cassie@devpost.com

**Comment by ShMcK** [comment]
Closing as stale
