### ISSUE TITLE
Talk Proposal: Building A Site Builder

### ISSUE THREAD

**Issue by pazooki** [VanJS/meetup#50]
- **Draft Title:**  Building A Site Builder
- **Length:** 20 Minutes
- **Links:** Available upon request (by the end of December)
- **Which dates, particularly Tue/Wed/Thu during the 2nd/3rd week of a month, are you likely available?** (Tues 24th OR Wed 25th OR Thu 26th), January 2023

The focus of this talk is about the journey of creating a Website/App builder with pure JavaScript and the lessons learned in the process. In this talk we cover concepts and architecture design decisions made to build such a framework that is general and efficient enough to be used as a Low-code Development Platform (LCDP).  We dive deep into the code and explain how some of the main problems were solved.

### Speaker Bio
- **Name:** Mehrdad Pazooki
- **Mini-bio:** Tech Entrepreneur
- **Would you like help with your presentation?** (feedback on slides) Yes
- **Social media link(s):**  https://www.linkedin.com/in/mrdpzk mrdpzk@gmail.com
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?** Yes

**Comment by AkimaLunar** [comment]
Hey, @pazooki! VanJS is not doing events at the moment, as far as I know. Reach out to Simon from ReactVancouver. They still have regular meetings.

**Comment by ShMcK** [comment]
Hi @pazooki, VanJS has started up again. 
If you're still interested in giving a talk, follow up in this thread.
