### ISSUE TITLE
Talk Proposal: Using CodeQL to secure the World's JavaScript at GitHub

### ISSUE THREAD

**Issue by aeisenberg** [VanJS/meetup#51]
- **Draft Title:** Using CodeQL to secure the World's JavaScript at GitHub
- **Length:** 20 min
- **Links:** (slides, article, notes) I don't have the slides yet, but it will be loosely based on this Capture the Flag exercise: https://securitylab.github.com/ctf/jquery/ Or I might use the example of binary planting from this blog post: https://github.blog/2022-04-19-sharing-security-expertise-through-codeql-packs-part-i/
- **Which dates, particularly Tue/Wed/Thu during the 2nd/3rd week of a month, are you likely available?** Wednesdays in April are generally good.

CodeQL is a static analysis engine used by developers to automate security checks, and by security researchers to perform variant analysis. In CodeQL, code is treated like data. Security vulnerabilities, bugs, and other errors are modeled as queries that can be executed against databases extracted from code. 

In this talk, I will introduce CodeQL for JavaScript, how to use it to creates databases, how to write simple queries to find code vulnerabilities in JavaScript, and I will walk you through a real-world JavaScript vulnerability that was discovered through the use of CodeQL.

CodeQL is created by GitHub and free for research and open source use.

### Speaker Bio
- **Name:** Andrew Eisenberg
- **Mini-bio:** Andrew is an engineer at GitHub who is building extensibility into the CodeQL compiler. He has a PhD from UBC and calls Vancouver his home.
- **Would you like help with your presentation?** (feedback on notes, practice run)
- **Social media link(s):** 
    - https://linkedin.com/in/aeisenberg/ 
    - https://mastodon.social/@aeisenberg
    - https://twitter.com/werdnagreb
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?** Yes. 100%

**Comment by ShMcK** [comment]
@aeisenberg would Wednesday, April 26th work for you?

**Comment by aeisenberg** [comment]
Yes. That works for me. Thank you!

**Comment by aeisenberg** [comment]
Here are the slides I'm working on:

https://docs.google.com/presentation/d/1kwRjMk4b51ZMVSnFXOqz8RBYgIRoapdERYKDFf-O_z4/edit#slide=id.g5449cee635_0_19
