### ISSUE TITLE
Talk Proposal:  Introduction to ChatGPT & GPT-4 API

### ISSUE THREAD

**Issue by ykdojo** [VanJS/meetup#52]
- **Draft Title:** Introduction to ChatGPT & GPT-4 API
- **Length:** 10 min lightning-ish talk
- **Links:** https://www.loom.com/share/a46c58cdcd9a4a0584740791b0f6ac3f

Learn how to get started with ChatGPT & GPT-4 APIs.

They're by far the most advanced large language models in the market, and in this talk, you'll learn how they work and how to put different components together to create your own AI-powered app.

ChatGPT & GPT-4 are the new platform of our generation, just like how the iPhone & smartphones were a platform that kickstarted the journey of many, many startups.

So let's dive into how to take advantage of it.

### Speaker Bio
- **Name:** YK aka CS Dojo
- **Mini-bio:** Creator of CS Dojo, a programming education YouTube channel with 1.8M+ subscribers. Also active on a few other platforms including Twitter, giving tips on coding, AI, and a career in tech. Currently, a founding engineer at an AI startup.
- **Would you like help with your presentation?** No that's ok - thank you. Will it be recorded?
- **Social media link(s):** https://twitter.com/ykdojo
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?** Yes.

**Comment by ShMcK** [comment]
> Will it be recorded?

We don't usually record events, but I can look into it.

**Comment by ShMcK** [comment]
I've updated the presentation on the site.
Thank you so much covering this ever-changing topic!
