### ISSUE TITLE
Talk Proposal: How Pointless Projects Made my Career

### ISSUE THREAD

**Issue by jonnyk20** [VanJS/meetup#53]
- How Pointless Projects Made my Career
- 5 min lightning talk
- No slides yet
- Available most Wednesdays with a few weeks' notice

In this brief talk, I'd like to share the story of going from completely non-technical to running a profitable software company on my own. I'll share about the projects that helped me learn to code, work as a dev, and then eventually jump ship to build my own ed-tech startup.

### Speaker Bio
- Jonny Kalambay
- Jonny is passionate about software and education. In March of 2022, he quit his comfortable job as a full-stack software engineer and has been building his own company, an ed-tech platform called Roshi.
- No need for help
- [Twitter](https://twitter.com/jonnykalambay) [LinkedIn](https://www.linkedin.com/in/jonnykalambay)
- I agree to the code of conduct

**Comment by ShMcK** [comment]
Johny would Wed, March 29th still work?
