### ISSUE TITLE
Talk Proposal: Reacting to Solid

### ISSUE THREAD

**Issue by blairbodnar** [VanJS/meetup#54]
- **Draft Title:** Reacting to Solid
- **Length:** Probably a 10-20 min presentation
- **Links:** Haven't started them yet 😅
- **Which dates** Could do the Wed, Apr 26 event if there's room for it. Any other times after that work too.

Still sorting out an idea, but figured I'd just submit a talk proposal now... which will force me to do some slides, haha. 😝. Probably:
* An overview of [SolidJs](https://www.solidjs.com/)
* Why I love it from a React developer's perspective

### Speaker Bio
- **Name:** Blair Bodnar 
- **Mini-bio:** Full Stack JavaScript Developer at Semios. Co-author of Rematch.
- **Would you like help with your presentation?** Should be ok. Will let you know if I do!
- **Social media link(s):** https://www.linkedin.com/in/blairbodnar
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?** Yes!

**Comment by ShMcK** [comment]
I was reading https://dev.to/this-is-learning/react-vs-signals-10-years-later-3k71 this morning and hoping someone would give a talk on the subject :) 

I'll put you down for Apr 26th!
