### ISSUE TITLE
Talk Proposal: Svelte(Kit) – It's what you don't see that makes it interesting

### ISSUE THREAD

**Issue by mikenikles** [VanJS/meetup#55]
- **Draft Title:** SvelteKit – It's what you don't see that makes it interesting
- **Length:** 20 min full presentation
- **Links:** None. It'll be live coding, maybe an intro / exit slide or two
- **Which dates, particularly Tue/Wed/Thu during the 2nd/3rd week of a month, are you likely available?** May 15+ with 2-3 weeks notice

In this talk, Mike starts with lessons learned over three years of exclusively developing full-stack applications with Svelte and SvelteKit (previously Sapper). The majority of the talk then focuses on various (web) concepts that Just Work™️ so you get to spend time on your project rather than boilerplate code. To wrap up, we will look at one of Mike's real-world products to explore what it all looks like combined and deployed to production, without any of the sweat and tears it takes to get to that point.

### Speaker Bio
- **Name:** Mike Nikles
- **Mini-bio:** Mike is a full-stack web developer with a focus on improving developer experience (aka save a business time & money).
- **Would you like help with your presentation?** I'm alright
- **Social media link(s):** [Twitter](https://twitter.com/mikenikles), [Website](https://www.mikenikles.com/), [LinkedIn](https://www.linkedin.com/in/mikenikles/)
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?** Yes

**Comment by ShMcK** [comment]
I haven't worked out the May Talks meetup yet, but I'll ping in here when we have a better idea.

**Comment by ShMcK** [comment]
@mikenikles Would Thursday, May 25th work for you?

**Comment by mikenikles** [comment]
Yes that works.

**Comment by mikenikles** [comment]
All good, that works too.
