### ISSUE TITLE
Talk Proposal: The best of ESLint rules

### ISSUE THREAD

**Issue by leonardofaria** [VanJS/meetup#56]
- **Draft Title: The best of ESLint rules** 
- **Length:** 15
- **Links:** TODO
- **Which dates, particularly Tue/Wed/Thu during the 2nd/3rd week of a month, are you likely available?** (e.g. "Most Thursdays with 4 weeks notice", "June or later", etc.)

Please replace this sentence with a short summary of your talk.

I want to share some rules and best practices that may make sense for your codebase.

### Speaker Bio
- **Name: Leo Faria** 
- **Mini-bio: Staff Engineer at Lattice, a collector of old Macs and a dog and cat person** 
- **Would you like help with your presentation? No** 
- **Social media link(s): https://leonardofaria.net** 
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?**

**Comment by ShMcK** [comment]
Leo, would you be interested in presenting in late May?

**Comment by leonardofaria** [comment]
Yes, lets do late May

**Comment by ShMcK** [comment]
@leonardofaria  Would Thursday, May 25th work for you?

**Comment by ShMcK** [comment]
Sorry, I just had to switch the date to Wednesday, May 24th due to a conflict at the venue. Does that work?
