### ISSUE TITLE
Talk Proposal:  PWA, the time has come

### ISSUE THREAD

**Issue by zlldnv** [VanJS/meetup#57]
- **Draft Title:** PWA, the time has come 
- **Length:** 20 Minutes 
- **Links:** It is in draft now
- **Which dates:** Anything after May 20

In this talk, I will explore the current state of Progressive Web Apps (PWA) and how they are transforming the way we build and use mobile applications. With Apple's recent introduction of push notifications for mobile Safari, the time is ripe to discuss the potential of PWAs and their ability to provide users with native app-like experiences. Attendees will learn about the latest PWA developments and best practices, and gain insights into how PWAs can drive engagement, conversions, and revenue for businesses of all sizes.

### Speaker Bio
- **Name:* Anton Zalaldinov* 
- **Mini-bio:** Anton Zalaldinov is a highly skilled software engineer with over 5 years of experience in developing complex web applications. He has worked with a range of technologies including JavaScript, React, and Node.js. Anton is passionate about building high-quality software solutions that solve real-world problems and is always eager to learn about new tools and techniques.
- **Would you like help with your presentation?: Yes** 
- **Social media link(s): https://www.linkedin.com/in/zalaldinov/** 
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)? Yes**

**Comment by ShMcK** [comment]
100% - With push notifications finally in mobile Safari, it is great timing. 

Would Wednesday, April 26th work for you to present?

Regarding help, if you'd like to give an early presentation over video, happy to provide feedback!
