### ISSUE TITLE
Talk Proposal: SSR Web Components with Enhance

### ISSUE THREAD

**Issue by brianleroux** [VanJS/meetup#58]
- **Draft Title:** SSR Web Components with Enhance
- **Length:** 15-20 min
- **Links:** enhance.dev
- **Which dates?** any Tue/Wed/Thu is ok

In this talk, we'll tour Enhance: a new way to build web apps with the pure web standards. No custom dialects to learn. No build steps to configure. No friction. Just you; building the web.

### Speaker Bio
- **Name:** Brian LeRoux
- **Mini-bio:** Cofounder of Begin, maintainer of OpenJS Architect and Enhance. Creator of wtfjs and old school JS hacker.
- **Would you like help with your presentation?** sure!
- **Social media link(s):** brianleroux on all the socials
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?** 💯%

**Comment by ShMcK** [comment]
Brian, would you be interested in presenting in late May?

If you need any help, I'm happy to provide feedback on an early draft or presentation. Let me know if you want to setup a call sometime.

**Comment by brianleroux** [comment]
Yeah, that works/ will do

**Comment by ShMcK** [comment]
@brianleroux would Thursday, May 25th work for you?

**Comment by brianleroux** [comment]
Yas! 🚀💕

**Comment by brianleroux** [comment]
Yep np!
