### ISSUE TITLE
Talk Proposal: TypeScript's problem - Type Puzzles

### ISSUE THREAD

**Issue by kei95** [VanJS/meetup#59]
**Draft Title:** TypeScript's problem - Type Puzzles

**Length (5 min lightning talk, or 10-20 min full presentation):** Aiming to make it about 15 min

**Links:** (slides, article, notes) Working on it!

**Which dates, particularly Tue/Wed/Thu during the 2nd/3rd week of a month, are you likely available?: (e.g. "Most Thursdays with 4 weeks notice", "June or later", etc.)** I'm flexible 

TypeScript is famous for its flexibility when it comes to typing thanks to the structural typing system. However, as you advance your skill and knowledge with it, you might have a greater chance to create custom types for niche usages. In this talk, I'll talk about why I won't encourage such usage in a project, and when you should do it.

### Speaker Bio
**Name:**  Kei

**Mini-bio (Tweet length is fine) :** A TypeScript lover ever since kicked start his professional career in 2019. Currently giving his big love on FE frameworks and React-Native with TypeScript.

**Would you like help with your presentation? (feedback on notes, practice run)** That would be great!

**Social media link(s):** **Twitter:** https://twitter.com/kei957 **Github:** https://github.com/kei95

**Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?** YES!

**Comment by ShMcK** [comment]
Hi Kei!

Would you be available to give the talk in late June? I don't have a date/venue yet, but hopefully soon.

**Comment by kei95** [comment]
> Hi Kei!
> 
> Would you be available to give the talk in late June? I don't have a date/venue yet, but hopefully soon.

Sure!

**Comment by ShMcK** [comment]
Hi Kei, 

I had you set for June, would be alright to move to July?
We have a sponsor for June, and they're looking to also provide speakers

**Comment by kei95** [comment]
> Hi Kei, 
> 
> 
> 
> I had you set for June, would be alright to move to July?
> 
> We have a sponsor for June, and they're looking to also provide speakers

Hey! All good. May I move it to August? I'm away from Vancouver in July

**Comment by ShMcK** [comment]
Sounds good, thanks Kei!

**Comment by ShMcK** [comment]
@kei95 Would August 22nd work for you?

**Comment by kei95** [comment]
> @kei95 Would August 22nd work for you?

That works. Thanks @ShMcK!

**Comment by ShMcK** [comment]
Great, I'll put you down for Aug 22nd :)
Link: https://www.meetup.com/vancouver-javascript-developers/events/295234628/
