### ISSUE TITLE
Talk Proposal: Understanding JavaScript proxies with a real-world use-case 

### ISSUE THREAD

**Issue by sivcan** [VanJS/meetup#60]
- **Draft Title:** Understanding JavaScript proxies with a real-world use-case
- **Length:** 15-20 mins full presentation
- **Links:** - TBD
- **Which dates, particularly Tue/Wed/Thu during the 2nd/3rd week of a month, are you likely available?** (e.g. "Most Thursdays with 4 weeks notice", "June or later", etc.): Thursday/Fridays with 2 weeks notice works well for me.

JavaScript Proxy is more like an advanced concept, and having it as a part of a JS developer's toolkit is definitely beneficial. I'll be breaking down and explaining how JS Proxy works. Then we'll be going through a real-world use-case of how we abstracted out our analytics system, lazy loaded it, and built multiple parts of the system all while the interface stayed clean and error-free for the rest of the hundreds of contributors of our code-base.
We'll understand how JS proxies work, and I also have a fun take-away project as a follow-up of the talk for folks to try their hands on later. 

### Speaker Bio
- **Name:** Sivcan Singh
- **Mini-bio:** Building virtual machinery at Postman Inc - https://postman.com.
- **Would you like help with your presentation?** (feedback on notes, practice run): I am good, thank you.
- **Social media link(s):**
  - https://twitter.com/sivcansingh
  - https://www.linkedin.com/in/sivcan/
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?** Yes

**Comment by ShMcK** [comment]
Love the topic. Can I put you down tentatively for late June? I can aim for a Thursday, no confirmed venue yet.

**Comment by sivcan** [comment]
@ShMcK Sure, that works.

**Comment by ShMcK** [comment]
Hi Sivcan, 

I had you set for June, would be alright to move to July?
We have a sponsor for June, and they're looking to also provide speakers

**Comment by sivcan** [comment]
@ShMcK Sure, July works.

**Comment by ShMcK** [comment]
@sivcan Would August 22nd work for you?

**Comment by ShMcK** [comment]
@sivcan would September 18th work for you?

**Comment by ShMcK** [comment]
Hi @sivcan, might October 18th work for you?

**Comment by ShMcK** [comment]
Noting available in January and beyond.

**Comment by bibschan** [comment]
Hey @sivcan would you be interested in speaking this March? We have a few tentative dates next month on the 20, 21, 27 or 28 of March. Let me know if you're interested and available!

**Comment by sivcan** [comment]
@bibschan Sorry I didn't get the notification from GitHub for this comment. I think I can plan something, if a slot is still open for March 20th. Let me know.

**Comment by bibschan** [comment]
@sivcan thanks for your reply! We are hosting demos instead of talks this month, so we can slot you in for April if that works for you! No firm dates yet but we'll likely get more info in the next couple of weeks, let me know if you're interested :)

**Comment by sivcan** [comment]
@bibschan Sure, April works!

**Comment by bibschan** [comment]
Hey @sivcan, we have a target date of April 23rd for the next meetup, would that date work for you? Let me know!

**Comment by sivcan** [comment]
@bibschan Yes, that works. Can you give a rough idea about the expected duration of the talk?

**Comment by bibschan** [comment]
> @bibschan Yes, that works. Can you give a rough idea about the expected duration of the talk?

Hey @sivcan, ideally 10min and max 15min, would that work for you? LMK!

**Comment by sivcan** [comment]
@bibschan Yes, that works. Thank you!

**Comment by bibschan** [comment]
@sivcan perfect! feel free to use the code SPEAKER to secure your meetup ticket here https://lu.ma/vanjs-april-2024

**Comment by z0r0ark** [comment]
@bibschan Thank you, signed up.

**Comment by bibschan** [comment]
hey @sivcan  I'm about to prepare the meetup slides and wondering if you'd like to have your picture on the speakers slide! If so, please send me a picture or link!
