### ISSUE TITLE
Talk Proposal: Craver: Past, Present and Future - Embracing Automation

### ISSUE THREAD

**Issue by GitHubTracey** [VanJS/meetup#61]
- **Draft Title:** Craver: Past, Present and Future - Embracing Automation
- **Length:** (5 min lightning talk, or 10-20 min full presentation) 15min
- **Links:** (slides, article, notes) In progress!
- **Which dates, particularly Tue/Wed/Thu during the 2nd/3rd week of a month, are you likely available?** (e.g. "Most Thursdays with 4 weeks notice", "June or later", etc.) Thurs in June 

Please replace this sentence with a short summary of your talk.

How a building a single app for a single client lead us down the path to a SASS company. Using automation to bring app build times from 5 weeks down to one hour, and the future goal of a one click app!

### Speaker Bio
- **Name:** Tracey Sum
- **Mini-bio:** (Tweet length is fine) I like to describe myself as a "lazy" developer. I love all things mobile, and automation. Let's make the developer experience better, and focus on the good stuff!
- **Would you like help with your presentation?** (feedback on notes, practice run) that would be great. I'm hoping to wrap up my first draft this coming week. 
- **Social media link(s):** (twitter, website, linkedin, etc.) linkedin: https://www.linkedin.com/in/tracey-sum-97490650/ 
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?** yes!

**Comment by ShMcK** [comment]
Thanks Tracy, looking forward to the talk. I've tagged it for June as discussed
