### ISSUE TITLE
Sponsor request: Craver Solutions - June 22nd, 2023 meetup

### ISSUE THREAD

**Issue by GitHubTracey** [VanJS/meetup#62]
## Information

Company name: Craver Solutions

Reason for sponsoring: (sales pitch? hiring? just because you love JavaScript?) we love Javascript, we also happen to be hiring for the backend (https://www.linkedin.com/jobs/view/3570834506)

Contact info: (email, linkedin or twitter is fine)
You can reach out to Tracey for details: tracey@craverapp.com
Craver Solutions Inc,
https://www.craverapp.com/

Logo: (either a link or an image that we can include in the slides)

We'll sponsor the food & drinks, thanks again, Shawn!

**Comment by ShMcK** [comment]
Let me know if there's any specific content or links you'd like called out in the event announcement.
