### ISSUE TITLE
Talk Proposal: How to Create Your Own Color System

### ISSUE THREAD

**Issue by cathcheeno** [VanJS/meetup#63]
- **Draft Title:** How to Create Your Own Color System
- **Length:** (5 min lightning talk, or 10-20 min full presentation) full presentation
- **Links:** (slides, article, notes) have not prepared yet, but I will present using GoogleSlide.
- **Which dates, particularly Tue/Wed/Thu during the 2nd/3rd week of a month, are you likely available?** (e.g. "Most Thursdays with 4 weeks notice", "June or later", etc.) the third week of the target month, all days are OK.

I will talk about the way to create a color system, which includes ideas such as:
- Light / Dark Mode
- User-select Color Theme
- Naming rules
- CSS Custom Properties, and the difference between its functionality and precessors' one
- Material Design 3 and Radix Colors
- oklch.

My presentation aims to give the audience basic techniques to kick-start creating their color system.

### Speaker Bio
- **Name:** Go Ohtani
- **Mini-bio:** (Tweet length is fine) Go Ohtani is a pure frontend developer with 13+ years of experience in Japan. He has been here in Vancouver for only two months.
- **Would you like help with your presentation?** (feedback on notes, practice run) I'm alright. I will let you know if I need help!
- **Social media link(s):** (twitter, website, linkedin, etc.) [LinkedIn](https://www.linkedin.com/in/go-ohtani/)
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?** YES

**Comment by ShMcK** [comment]
Hi Go! Thanks for the proposal. 
June seems to be booked up, but I'll try to find a spot as we plan out future events. Maybe July or August!

**Comment by cathcheeno** [comment]
@ShMcK 
> Maybe July or August!
OK, then I'll keep preparing for the presentation😀
Thank you for letting me konw!

**Comment by cathcheeno** [comment]
@ShMcK 
Hi! 
I have a question. There seems to be no July's talk on [the meetup event page](https://www.meetup.com/vancouver-javascript-developers/). Are we still having a talk event this month?

**Comment by ShMcK** [comment]
Sorry, I didn't manage to book a July event. 
We should be back for late August!

**Comment by cathcheeno** [comment]
OK, I got it. Thank you

**Comment by ShMcK** [comment]
@cathcheeno would you be available to talk on Aug 22nd?

**Comment by cathcheeno** [comment]
@ShMcK yes!
