### ISSUE TITLE
Talk Proposal: Domain-Driven Design in micro-frontend architecture

### ISSUE THREAD

**Issue by sr-shifu** [VanJS/meetup#64]
- **Draft Title:** Domain-Driven Design in micro-frontend architecture
- **Length:** (5 min lightning talk, or 10-20 min full presentation) full presentation
- **Links:** (slides, article, notes) Presentation is not ready yet but it will be based on my article: https://thesametech.com/domain-driven-design-in-micro-frontend-architecture/
- **Which dates, particularly Tue/Wed/Thu during the 2nd/3rd week of a month, are you likely available?** (e.g. "Most Thursdays with 4 weeks notice", "June or later", etc.) any day except Wed with 3 weeks notice

Tech talk will explore the application of Domain-Driven Design (DDD) principles in the context of micro-frontend architecture and highlight the versatility of DDD, explaining how it can be effectively employed in both backend and frontend development.  The talk introduces the concepts of subdomains and bounded contexts from DDD, showcasing their relevance in micro-frontend architecture. The speaker will also go through some practical mistakes made when applying DDD in the real-world projects.

### Speaker Bio
- **Name:** Ildar Sharafeev
- **Mini-bio:** (Tweet length is fine) Ildar is a software engineer, tech lead, double dad and coffee lover. He spent more than a decade in the industry, specializing in frontend and near-frontend tech. Ildar is passionate about micro-frontend and micro-service architectures, serverless computing, clean code, and reactive programming.
- **Would you like help with your presentation?** (feedback on notes, practice run) no, I am good
- **Social media link(s):** (twitter, website, linkedin, etc.)
   - My blog: https://thesametech.com/
   - My LinkedIn: https://www.linkedin.com/in/isharafeev/
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?** Yes

**Comment by ShMcK** [comment]
Thanks Ildar, I'll try to get some new events planned in the coming months for your talk!

**Comment by ShMcK** [comment]
Hi @sr-shifu. would you be interested in giving a talk on August 22nd?

**Comment by ShMcK** [comment]
@sr-shifu would you be interested in talking on Sept 18th?

**Comment by sr-shifu** [comment]
@ShMcK sorry can’t make it. Does Sep 19 or after work?
