### ISSUE TITLE
Talk Proposal: The Difference a Bottom-Up Approach to Component Planning Makes

### ISSUE THREAD

**Issue by derek-s-leung** [VanJS/meetup#65]
- **Draft Title:** The Difference a Bottom-Up Approach to Component Planning Makes
- **Length:** (5 min lightning talk, or 10-20 min full presentation) 5min lightning talk, though it’s currently a few min over
- **Links:** (slides, article, notes) In progress!
- **Which dates, particularly Tue/Wed/Thu during the 2nd/3rd week of a month, are you likely available?** (e.g. "Most Thursdays with 4 weeks notice", "June or later", etc.) Thurs in June coming up, I'm with Craver

A Lesson I learned in managing complexity over time

### Speaker Bio

- **Name:** Derek Leung
- **Mini-bio:** I’m a developer interested in everything there is to know, so I can build things well! I love making attractive UI, writing maintainable code, and finding ways to make React and React Native do my bidding.
- **Would you like help with your presentation?** (feedback on notes, practice run) It might be good to get some.
- **Social media link(s):** (twitter, website, linkedin, etc.) linkedin: https://www.linkedin.com/in/derek-s-leung
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?** Yes!

**Comment by ShMcK** [comment]
Hi Derek, would you be good for June 21st?

**Comment by ShMcK** [comment]
I've posted based on Tracey's notes, let me know if you want any content changes:
https://www.meetup.com/vancouver-javascript-developers/events/293856129/

**Comment by derek-s-leung** [comment]
Hi @ShMcK , I ended up changing topics! I have a talk manuscript and slides ready for the new topic.

**Comment by ShMcK** [comment]
Sounds good, I'll update the posting as well
