### ISSUE TITLE
Talk Proposal: React hooks behind the scenes and create own hook in NodeJs

### ISSUE THREAD

**Issue by guillezorrilla** [VanJS/meetup#66]
- **Draft Title: React Hooks behind the scenes, create your own hook in NodeJs** 
- **Length:** (5 min lightning talk, or 10-20 min full presentation)
- **Links:** (slides, article, notes)
- **Which dates, particularly Tue/Wed/Thu during the 2nd/3rd week of a month, are you likely available?** (e.g. "Most Thursdays with 4 weeks notice", "June or later", etc.) Thurs in June coming up, I'm with Craver

A practical guide on hook react hooks works behind the scenes, for useState and useEffect mainly, also creating a custom NodeJs useState hook to update data in node

### Speaker Bio
- **Name: Guillermo Zorrilla** 
- **Mini-bio:** I'm a front-end developer who loves coding and clean arquitecture, focused on performance and delivering best posible products.
- **Would you like help with your presentation?** Yeah, some help would be nice
- **Social media link(s):** [(twitter, website, linkedin, etc.)](https://www.linkedin.com/in/gzorrilla/)
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)? Yes**

**Comment by ShMcK** [comment]
Hi Guillermo, would you be good for June 21st?
