### ISSUE TITLE
Talk Proposal: Wait, you're using React Native on the Web?!

### ISSUE THREAD

**Issue by tazsingh** [VanJS/meetup#67]
Title: Wait, you're using React Native on the Web?!
Length: 20-30 minutes
Link to video: https://guild.host/presentations/wait-youre-shipping-7sui24
Dates: I'll only be in Vancouver from July 24th-31st, if that works!

Summary:
Taz will dive into the skepticism of building React Native Apps for the Web, including everything from design systems and navigation to ExpoGL and Reanimated, from how they’ve successfully built Guild on top of this architecture.

Please see the video recording from the Chain React Conference from a few months ago above. It was well received by that audience.

### Speaker Bio
Name: Taz Singh
Bio: Taz is the Founder of Guild and long time participant in communities around the world. He has over two decades of software experience ranging from video games & robotic AI to consumer application development, has served as a principal technical management consultant, and is a serial startup founder. When he's not behind his computer, he can be found chasing his cat around the house or being chased by cars around a race track.

- Would I like help: No
- Social Links: https://twitter.com/tazsingh
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?** Yes

**Comment by ShMcK** [comment]
Hi Taz, juding by the "I'll only be in Vancouver from July 24th-31st" I think we missed this one!
