### ISSUE TITLE
Talk Proposal: X Marks the Spot: Charting the Course to Complex UI with XState

### ISSUE THREAD

**Issue by 10thfloor** [VanJS/meetup#68]
- **Draft Title:** State Machines are still cool.
- **Length:** 10-20 minutes
- **Links:** TBD

Arc'teryx Front-End dev will elaborate on why you should be using state-machines, and share their thoughts and experience using XState to re-design and develop their new checkout.

### Speaker Bio
- **Name:**  Mackenzie Kieran
- **Mini-bio:** Lead Front-End developer and manager at Arc'teryx. 
- **Would you like help with your presentation?** (feedback on notes, practice run) No thanks!
- **Social media link(s):** (twitter, website, linkedin, etc.) 
@10thfloor on X, 
Linkedin: https://www.linkedin.com/in/mackenzie-kieran-9790882b/

- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?** Yes

**Comment by ShMcK** [comment]
As a big fan of XState, I'm very much looking forward to your talk!
