### ISSUE TITLE
Talk Proposal: One approach for reusable components using a data + format response

### ISSUE THREAD

**Issue by plinioprado** [VanJS/meetup#70]
- **Draft Title:** One approach for reusable components using a data + format response
- **Length:** 10-20 min full presentation
- **Links:** None
- **Which dates, particularly Tue/Wed/Thu during the 2nd/3rd week of a month, are you likely available?** any

**One approach for reusable components using a data + format response**
Helping to handle the swarm of auxiliary tables that fly around your main features
Content would be built based on top of https://github.com/plinioprado/ctr-client-react-base1 and maybe its NodeJs simple server (https://github.com/plinioprado/ctr-server-node-base1)

Note the original proposal for this talk included another option that can be left for a future date.
"Differences between coding React in 2017 and 2023"
Not for historical curiosity but because there is a lot of legacy around.
Content would be based on what http://plinioprado.com/#/ctr-react-2017-2023

### Speaker Bio
- **Name:** Plinio Prado
- **Mini-bio:** Developer of Business and Finance software after a long time using them
- **Would you like help with your presentation?** Yes, choice of option then a review of the actual slides
- **Social media link(s):** https://www.linkedin.com/in/plinioprado
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?** Yes

**Comment by ShMcK** [comment]
One vote for the data + format approach, I haven't seen that before, curious to learn more!

**Comment by ShMcK** [comment]
@plinioprado would October 18th work for you?

**Comment by plinioprado** [comment]
@ShMcK 
Sure I can replan for Oct/18.
Give me until this Friday to put some slides together and I will confirm

**Comment by plinioprado** [comment]
> @ShMcK Sure I can replan for Oct/18. Give me until this Friday to put some slides together and I will confirm

Confirmed. I can present on Oct/18
