### ISSUE TITLE
Talk Proposal: A Fresh Look at Isomorphic Rendering

### ISSUE THREAD

**Issue by CAYdenberg** [VanJS/meetup#71]
- **Draft Title:** A Fresh Look at Isomorphic Rendering
- **Length:** 20 minutes
- **Links:** (talk not yet available)
- **Which dates, particularly Tue/Wed/Thu during the 2nd/3rd week of a month, are you likely available?** (Thursdays are best, Wednesday's work, and Tues are usually ok except following a holiday Monday)

React and the frontend frameworks inspired by it have created an unprecedented era of innovation in programming highly interactive web experiences. Nobody wants to go back. But rendering entire applications in the browser has also created headaches. Fresh is a whole new take that drastically minimizes the amount of JavaScript needed to power rich experiences. Based on Deno and Preact, it eliminates a lot of bloat both in dependencies and boilerplate.

### Speaker Bio
- **Name:** Casey Ydenberg
- **Mini-bio:** Freelance web developer, former academic, data nerd, dad, mediocre oboist
- **Would you like help with your presentation?** no
- **Social media link(s):** [LI](https://www.linkedin.com/in/caydenberg/), [Mastadon](https://indieweb.social/@casey)
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?** Yes

**Comment by ShMcK** [comment]
@CAYdenberg would you be interested in presenting on Oct 18th?

**Comment by CAYdenberg** [comment]
No - I'm already speaking at van data vis on Oct 17 so that's too much for next week. Can I do the next one?

**Comment by ShMcK** [comment]
I can put you down for November, if that works?

**Comment by CAYdenberg** [comment]
Probably - what date?

**Comment by ShMcK** [comment]
I'll try to get a date confirmed. Likely Nov 21st or Nov 23rd.

**Comment by ShMcK** [comment]
I can confirm the date, Nov 21st @CAYdenberg would that work for you?

**Comment by CAYdenberg** [comment]
That's great, thanks!
