### ISSUE TITLE
Talk Proposal: Generate API specs for any app or website

### ISSUE THREAD

**Issue by AndrewWalsh** [VanJS/meetup#73]
- **Draft Title:** - Generate API specs for any app or website
- **Length:** (5 min lightning talk, or 10-20 min full presentation) - 5 min lightning talk
- **Links:** (slides, article, notes) - I will work on this, just want to confirm first
- **Which dates, particularly Tue/Wed/Thu during the 2nd/3rd week of a month, are you likely available?** (e.g. "Most Thursdays with 4 weeks notice", "June or later", etc.) - I'm flexible

The talk will be a presentation of [OpenAPI DevTools](https://github.com/AndrewWalsh/openapi-devtools). I will cover use cases for the tool, and how it works.

### Speaker Bio
- **Name:** Andrew Walsh
- **Mini-bio:** (Tweet length is fine) Software Engineer based in Vancouver
- **Would you like help with your presentation?** (feedback on notes, practice run) No
- **Social media link(s):** (twitter, website, linkedin, etc.) - https://www.linkedin.com/in/andrew--walsh/
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?** Yes

**Comment by ShMcK** [comment]
@AndrewWalsh 

Thanks Andrew, OpenAPI devtools looks amazing.

If you only need 5 minutes, do you want to present on Tuesday, Nov 21st?

**Comment by AndrewWalsh** [comment]
Thanks @ShMcK ! I can't make that day unfortunately, but I'll definitely be free for the next meet.

**Comment by bibschan** [comment]
Hey @AndrewWalsh! Just wanted to follow up here, would you be open to talking at VanJS in March? We are thinking these dates 20, 21, 27 or 28 of March but nothing locked yet. Let me know!

**Comment by AndrewWalsh** [comment]
@bibschan Ah unfortunately I won't be able to, I won't be in Canada for much longer and those dates. Will close this, thanks though.
