### ISSUE TITLE
Talk Proposal: Exploring Hono

### ISSUE THREAD

**Issue by kimizuy** [VanJS/meetup#74]
- **Draft Title:** Exploring Hono
- **Length:** 10min
- **Links:** Work in progress
- **Which dates, particularly Tue/Wed/Thu during the 2nd/3rd week of a month, are you likely available?** I'm flexible

Hono is a lightweight and minimal web framework similar to Express. It works with various runtimes such as Edge, deno, and bun.

https://hono.dev/top

### Speaker Bio
- **Name:** Kimizu Yamasaki
- **Mini-bio:** A front-end engineer specializing in React and TypeScript
- **Would you like help with your presentation?** Yes. I'm not a native English speaker, so I'd like to have someone check my English.
- **Social media link(s):** https://kimizuy.dev/
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?** Yes!

**Comment by bibschan** [comment]
Hey @kimizuy! Would you be interested in speaking this March? We have a few tentative dates next month on the 20, 21, 27 or 28 of March. Let me know if you're interested and available!

**Comment by bibschan** [comment]
Hey @kimizuy let me know if you're still interested in giving a talk at VanJS, otherwise I'll close this issue :)

**Comment by bibschan** [comment]
@kimizuy perfect! Can you put you tentatively on for June?

**Comment by kimizuy** [comment]
@bibschan Sorry I said, "after May", but I meant to include May too. In any case, both May and June are available!

**Comment by bibschan** [comment]
oh perfect! I'll put you down for May then :) thanks a bunch. You can get your free ticket using code `SPEAKER` here https://lu.ma/vanjs-may-2024

**Comment by bibschan** [comment]
@kimizuy would you be able to send me a picture of yourself that I can use for our introduction slides? thank you!

**Comment by kimizuy** [comment]
@bibschan Hi, I have sent my picture to your email address. Thank you

**Comment by bibschan** [comment]
@kimizuy you mentioned in your description you'd like some help with checking your slides, let me know if you want me to review! :)
