### ISSUE TITLE
Demo Proposal: Testing with Playwright

### ISSUE THREAD

**Issue by mootoday** [VanJS/meetup#75]
- **Draft Title:** Testing with Playwright
- **Length:** 10 min

We're going to learn how we can leverage Playwright ([playwright.dev](https://playwright.dev/)) to write end-to-end tests for web applications. We won't even have to write much code!

### Speaker Bio (optional)
- **Name:** Mike Nikles
- **Mini-bio:** Mike is the founder of [webstone.app](https://webstone.app/), a full-stack web education platform.
- **Would you like help with your demo?** I'm alright
- **Social media link(s):** [Twitter](https://twitter.com/mootoday)
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?** Yes

**Comment by bibschan** [comment]
@mootoday Hey Mike! Looking forward to your demo later today :) just wanted to give you a heads up on the presentation order so you can prepare in advance -- you are going to be the 1st on the list. Let me know if you have any questions, see you soon!

**Comment by mikenikles** [comment]
Thanks for the heads up. See you tonight.
