### ISSUE TITLE
Demo Proposal: AutoDev: Automated AI-Driven Development

### ISSUE THREAD

**Issue by ShMcK** [VanJS/meetup#76]
- **Draft Title:** AutoDev: Automated AI-Driven Development
- **Length:** 10 min

A breakdown of a recent paper titled "AutoDev: Automated AI-Driven Development".
https://arxiv.org/html/2403.08299v1

### Speaker Bio
- **Name:** Shawn McKay
- **Mini-bio:** Staff Software Eng at Amplitude, software hobbyist
- **Social media link(s):** https://www.linkedin.com/in/shmck/
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?** yes!

**Comment by ShMcK** [comment]
Notes: 
![Notes](https://github.com/VanJS/meetup/assets/4660659/55c571bc-1a66-4103-80cc-e0b4a11194e2)

**Comment by bibschan** [comment]
@ShMcK Hey Shawn! Looking forward to your demo later today :) just wanted to give you a heads up on the presentation order so you can prepare in advance -- you are going to be the 5th on the list. Let me know if you have any questions, see you soon!
