### ISSUE TITLE
Demo Proposal: Hot Chocolate Festival Project

### ISSUE THREAD

**Issue by fessehaye** [VanJS/meetup#77]
- **Draft Title:** Hot Chocolate Festival Project
- **Length:** (5 min ~ 10 min)

Going to show a site I made for the Vancouver Hot Chocolate Festival 2024. Small personal project using Vite, React, Tailwind, and Antd design.

### Speaker Bio (optional)
- **Name:**  Simon Fessehaye
- **Mini-bio:** Frontend Developer based in Vancouver
- **Would you like help with your demo? I am good!
- **Social media link(s): https://www.simonfessehaye.com/
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?** Yes

**Comment by bibschan** [comment]
@fessehaye  Hey Simon! Looking forward to your demo later today :) just wanted to give you a heads up on the presentation order so you can prepare in advance -- you are going to be the 2nd on the list. Let me know if you have any questions, see you soon!
