### ISSUE TITLE
Demo Proposal: React Three Fiber 

### ISSUE THREAD

**Issue by Ajuska** [VanJS/meetup#78]
- **Draft Title:** React Three Fiber: How to overengineer your wedding web
- **Length:** 10 min

A story behind developing our fancy 3D wedding web showcasing capabities of Three.js and React.

### Speaker Bio (optional)
- **Name:**  Andrea & Ondra Vicar
- **Mini-bio:** Software developers seeking new adventures
- **Would you like help with your demo?** No, thank you
- **Social media link(s):** [Andrea's linkedin](https://www.linkedin.com/in/andrea-vicarova/), [Ondra's linkedin](https://www.linkedin.com/in/ondrej-vicar/)
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?** Yes

**Comment by bibschan** [comment]
@Ajuska Hey Andrea! Looking forward to your demo later today :) just wanted to give you a heads up on the presentation order so you can prepare in advance -- you are going to be the 3rd on the list. Let me know if you have any questions, see you soon!
