### ISSUE TITLE
Demo Proposal: Responsive, interactive charts composed in JSX

### ISSUE THREAD

**Issue by CAYdenberg** [VanJS/meetup#79]
- **Draft Title:** Responsive interactive charts composed in JSX
- **Length:** 10 min

Responsive design and touch interaction present new opportunities and challenges for data visualization on the web. Here I present pvalue, a flexible JSX-based library for authoring charts. Pvalue "bakes in" responsive design, pointer events, and component-based composition to allow chart authors to work with the grain of the web medium and create experiences that today's users expect.

### Speaker Bio (optional)
- **Name:** Casey A. Ydenberg
- **Mini-bio:** Former molecular biologist turned frontend developer, freelancer, data-vis enthusiast, mediocre oboist
- **Would you like help with your demo?** I'm good
- **Social media link(s):** https://livingpixel.io
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?** Yes

**Comment by bibschan** [comment]
@CAYdenberg  Hey Casey! Looking forward to your demo later today :) just wanted to give you a heads up on the presentation order so you can prepare in advance -- you are going to be the 4th on the list. Let me know if you have any questions, see you soon!
