### ISSUE TITLE
Demo Proposal: Lirdle (a parody of W*rdl*)

### ISSUE THREAD

**Issue by ericpromislow** [VanJS/meetup#80]
- **Draft Title:** Lirdle: Developing and Running a Lightweight Low-Attack-Surface Site
- **Length:** 10 mins.

Lirdle is a parody of a certain well-known daily word-guessing puzzle. The client-side is a classic VanillaJS+VanillaCSS+VanillaHTML site. But there are some interesting things going on server-side to deliver performance and a community feel without requiring logins or an application server.

### Speaker Bio (optional)
- **Name:** Eric Promislow
- **Mini-bio:** Builds cloud infrastructure and dev tools for work, builds useful/maddening/frivolous sites for fun
- **Would you like help with your demo?** No, I'm good
- **Social media link(s):** [(twitter, website, linkedin, etc.)](https://duckduckgo.com/?t=ffab&q=%22Eric+Promislow%22&ia=web)
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?** Of course.

**Comment by bibschan** [comment]
@ericpromislow Hey Eric! Looking forward to your demo later today :) just wanted to give you a heads up on the presentation order so you can prepare in advance -- you are going to be the 6th on the list. Let me know if you have any questions, see you soon!

**Comment by ericpromislow** [comment]
Sounds good. Just pls change my email to ***@***.*** - you
sent this to my work address (prob because of github)
