### ISSUE TITLE
Demo Proposal: Expo - the modern mobile app development with JS

### ISSUE THREAD

**Issue by kei95** [VanJS/meetup#81]
- **Draft Title:** Expo. How far has modern mobile development come?
- **Length:** 10min

If you are not actively hunting down their news, you might not have an idea of how modern React Native can provide a similar experience as web development. Showcasing new capability with the latest version of Expo. It'll introduce; 1. Expo router (file base routing) 2. Its API route.

### Speaker Bio (optional)
- **Name:** Kei
- **Mini-bio:** (Tweet length is fine)A FrontEnd dev with passion for TypeScript and React Native
- **Would you like help with your demo?** (feedback on notes, practice run) I should be fine
- **Social media link(s):** (twitter, website, linkedin, etc.) [linkedIn](https://www.linkedin.com/in/keisuke-yamashita-075164178/) [Twitter](https://twitter.com/kei957)
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?** Yes!

**Comment by kei95** [comment]
@ShMcK Sorry for the last-minute update! 🙏

**Comment by bibschan** [comment]
@kei95 Hey Kei! Looking forward to your demo later today :) just wanted to give you a heads up on the presentation order so you can prepare in advance -- you are going to be the 7th on the list. Let me know if you have any questions, see you soon!
