### ISSUE TITLE
Demo Proposal: A quick tour of building a React Native app in 2024

### ISSUE THREAD

**Issue by brentvatne** [VanJS/meetup#82]
- **Draft Title:** A quick tour of building a React Native app in 2024
- **Length:** (5 min ~ 10 min) 15 mins (discussed with @ShMcK)

React Native is back and better than ever. Expo is a framework [recommended by Meta](https://github.com/react-native-community/discussions-and-proposals/blob/main/proposals/0759-react-native-frameworks.md) for building production apps with React Native. Rather than just saying a bunch of words, I'll show you what this all means and why I think React Native with Expo is the best way to build most mobile apps in 2024.

### Speaker Bio (optional)
- **Name:** Brent Vatne
- **Mini-bio:** Web/mobile developer working on Expo and React Native
- **Would you like help with your demo?** Not necessary, thanks!
- **Social media link(s):** https://twitter.com/notbrent https://github.com/brentvatne https://expo.dev/
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?** yes

**Comment by brentvatne** [comment]
note: this does not conflict with #81 - I will not cover the topics that @kei95 intends to. It may make sense to have my demo go first though, since it could be useful context for the audience before @kei95's demo.

**Comment by kei95** [comment]
Hi @brentvatne it's nice to know you'll be at the event! I didn't know a dev in Expo team was in this town😳 I honestly feel sooo much pressure to give a talk in front of someone from the real Expo team 😂 Nonetheless, I'm looking forward to seeing you at the conf! 

![giphy](https://github.com/VanJS/meetup/assets/44686790/2b459f35-fdbf-4fef-a880-926c33d16931)

**Comment by bibschan** [comment]
@brentvatne Hey Brent! Looking forward to your demo later today :) just wanted to give you a heads up on the presentation order so you can prepare in advance -- you are going to be the 8th on the list. Let me know if you have any questions, see you soon!
