### ISSUE TITLE
Demo Proposal: Building a Mini, Browser-Based, Client-Side Video Editor

### ISSUE THREAD

**Issue by damzobridge** [VanJS/meetup#83]
- **Draft Title:**  Building a Mini, Browser-Based, Client-Side Video Editor
- **Length:** (5 min ~ 10 min): 6-8 mins

I'll be breaking down how I built a mini video-editor that works completely in the browser using Javascript, WebGL, and a game engine.

### Speaker Bio (optional)
- **Name:** Adam Madojemu
- **Mini-bio:** Full-stack Web/Game Developer, working at the intersection of media and tech. 
- **Would you like help with your demo?** I'm good, but thank you!
- **Social media link(s):** https://www.adammadojemu.com/
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?** Yes

**Comment by bibschan** [comment]
@damzobridge Hey Adam! Looking forward to your demo later today :) just wanted to give you a heads up on the presentation order so you can prepare in advance -- you are going to be the 9th on the list. Let me know if you have any questions, see you soon!

**Comment by damzobridge** [comment]
> @damzobridge Hey Adam! Looking forward to your demo later today :) just wanted to give you a heads up on the presentation order so you can prepare in advance -- you are going to be the 9th on the list. Let me know if you have any questions, see you soon!

Sounds good, thank you!
