### ISSUE TITLE
Talk Proposal: Beyond React - Building interactive web apps with HTMX and Alpine.js

### ISSUE THREAD

**Issue by numan** [VanJS/meetup#84]
- **Draft Title:** Beyond React - Building interactive web apps with HTMX and Alpine.js
- **Length:** 20 mins
- **Links:** WIP
- **Which dates, particularly Tue/Wed/Thu during the 2nd/3rd week of a month, are you likely available?** Flexible, but need 2-3 weeks of notice

React is an amazing framework that allows you to build highly interactive user interfaces, but it comes with tradeoffs. This talk will discuss some of those tradeoffs and present an alternative to building interactive apps using HTMX and Apline.js. We will also demo WhaleCast, an interactive app that keeps you informed about your favourite podcast.

### Speaker Bio
- **Name:** Numan Sachwani
- **Mini-bio:** Entrepreneur and a multi-time startup founder
- **Would you like help with your presentation?** Feedback would be good
- **Social media link(s):** (twitter, website, linkedin, etc.) https://www.linkedin.com/in/numan-sachwani-59090911
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?**

**Comment by bibschan** [comment]
Hey @numan, we have a target date of April 23rd for the next meetup, would that date work for you? Let me know!

**Comment by numan** [comment]
> Hey @numan, we have a target date of April 23rd for the next meetup, would that date work for you? Let me know!

Yes, I can make that work

**Comment by bibschan** [comment]
@numan Sounds great! Excited to have you! I will DM you the promo code you can use to secure your ticket :)

**Comment by bibschan** [comment]
@numan I'm wondering if you would be open to speaking in May instead (https://lu.ma/vanjs-may-2024)? Let me know if this would work for you. We're trying to shuffle some things around to slot in a speaker who's been waiting for a year -- sorry about the that! LMK :)

**Comment by numan** [comment]
Yes, that's fine

**Comment by bibschan** [comment]
hey @numan, you can get your free ticket using code `SPEAKER` here https://lu.ma/vanjs-may-2024

**Comment by bibschan** [comment]
@numan would you be able to send me a picture of yourself that I can use for our introduction slides? thank you!
