### ISSUE TITLE
Talk Proposal: Using SOLID principles to improve code quality. 

### ISSUE THREAD

**Issue by brunagarcia** [VanJS/meetup#86]
- **Draft Title:** Using SOLID principles to improve code quality. 
- **Length:** 10-20 min full presentation
- **Links:** [Google Slides](https://docs.google.com/presentation/d/1Wto3M1bDLlqElw6AkYNS9EAa90TTWpd3RmREmk6z5xg/edit?usp=sharing) and [Code Examples](https://replit.com/@BrunaGarcia/SOLID)
- **Which dates, particularly Tue/Wed/Thu during the 2nd/3rd week of a month, are you likely available?** Most Wednesdays and Thursdays with a week notice. April or later months would work for me. 

Presentation on what are the SOLID principles and how to use and think about them when writing your code to improve code quality. 

### Speaker Bio
- **Name:** Bruna Garcia (she/her)
- **Mini-bio:** Full Stack software developer at Zesty.ai - Dog mom, star trek enthusiast always down to learn new things. 
- **Would you like help with your presentation?** Would love feedback and maybe a practice run 😬
- **Social media link(s):** [Linkedin](www.linkedin.com/in/brunagarciap91) [Twitter](https://twitter.com/bruna_garciap)
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?** **Yes**

**Comment by bibschan** [comment]
Hey @brunagarcia, we have a target date of April 23rd for the next meetup, would that date work for you? Let me know!

**Comment by brunagarcia** [comment]
Hey @bibschan. The 23rd works for me! Thanks

**Comment by bibschan** [comment]
@brunagarcia  Sounds great! Excited to have you! I will DM you the promo code you can use to secure your ticket :)

**Comment by bibschan** [comment]
hey @brunagarcia I'm about to prepare the meetup slides and wondering if you'd like to have your picture on the speakers slide! If so, please send me a picture or link!
