### ISSUE TITLE
Demo Proposal: ExpressoTS :: The Developer-Friendly TypeScript/Javascript Framework for Server-Side Applications

### ISSUE THREAD

**Issue by rsaz** [VanJS/meetup#87]
- **Draft Title:** ExpressoTS :: The Developer-Friendly TypeScript/Javascript Framework for Server-Side Applications
- **Length:** (10 min)

Please replace this sentence with a short summary of your demo.
The purpose of the Demo is to show the power and capabilities of the ExpressoTS Framework for backend development using Typescript or Javascript.

### Speaker Bio (optional)
- **Name:** Richard Zampieri
- **Mini-bio:** Principal Engineer, ExpressoTS Creator, GitHub Brazil Maintainer, Co-Author of ISO Standard ISO/AWI 23725 (Interface for Autonomous System)
- **Would you like help with your demo?** (feedback on notes, practice run) : Practice run
- **Social media link(s):** (twitter, website, linkedin, etc.)
> Twitter: @expressots
> Website: https://expresso-ts.com/
> Linked in: https://www.linkedin.com/in/richardzampieri/
> Email: richard.zampieri@expresso-ts.com

- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?**
Yes, I agree with the code of conduct.

**Comment by rsaz** [comment]
Hi @ShMcK, thank you for your attention to this matter. Do we have any tentative dates for when the next VanJS meetup might take place? Additionally, I wanted to share that I am in the final stages of setting up our new office in Burnaby. I'm allocating some space specifically for tech gatherings and the promotion of technology. I'm hopeful that, in the future, this could serve as a venue for a VanJS meeting as well.

I aim to champion technology within our organization to foster and strengthen a robust software engineering culture at our workplace.

**Comment by ShMcK** [comment]
Hi @rsaz, congrats on the new office!

We've just confirmed the next 3 dates for VanJS. 
We'd be looking for a venue for July and beyond. We can also consider running additional events - there seems to be demand. 

Let us know if you'd be interested in speaking April, May or June

**Comment by rsaz** [comment]
Hi @ShMcK thank you! Yes, I can speak on April.

**Comment by bibschan** [comment]
@rsaz We have a confirmed date of April 23rd, let me know if that works for you. I just sent you a DM on LinkedIn with the promo code for your meetup ticket :)

**Comment by rsaz** [comment]
Hi @bibschan it works. I already replied on Linked in and registered with the promo code. Also, I am asking the community manager here to repost your post on Linked in for the event. Thank you

**Comment by rsaz** [comment]
Hi @ShMcK and @bibschan , how are you?

How much time do I have available to present? I do have a small .ppt + demo. 
Do I need to bring anything else other than my laptop?

Thank you!

**Comment by bibschan** [comment]
hey @rsaz ideally we like to keep it within 10 minutes, with a max of 15min. Does this sound good? Just your laptop is enough! Let me know if you have any other questions!

**Comment by rsaz** [comment]
> hey @rsaz ideally we like to keep it within 10 minutes, with a max of 15min. Does this sound good? Just your laptop is enough! Let me know if you have any other questions!

All good, 15min is enough. 5min to the pres. + 10 to the demo. Thanks.

**Comment by bibschan** [comment]
hey @rsaz I'm about to prepare the meetup slides and wondering if you'd like to have your picture on the speakers slide! If so, please send me a picture or link!

**Comment by rsaz** [comment]
> hey @rsaz I'm about to prepare the meetup slides and wondering if you'd like to have your picture on the speakers slide! If so, please send me a picture or link!

Hi @bibschan here is the pic:

![richard](https://github.com/VanJS/meetup/assets/4088378/d818a3e7-2f30-4dd1-aa48-923bdccf9970)

**Comment by bibschan** [comment]
thank you ✨ @rsaz you mentioned you'd like to have a practice run, please arrive at the venue 5:15pm if possible so that we have enough time! :)
