### ISSUE TITLE
Talk Proposal: How using xState simplified our complex screens

### ISSUE THREAD

**Issue by benjaminkomen** [VanJS/meetup#88]
- **Draft Title:** How using xState simplified our complex screens
- **Length:** 10-15 minute presentation
- **Links:** https://stately.ai/docs/
- **Which dates, particularly Tue/Wed/Thu during the 2nd/3rd week of a month, are you likely available?** I can do April 23rd

My team is developing a mobile app using React Native. One of our screens accumulated increasingly more complex states, starting with a view and edit mode, then updates being in progress etc. Modelling all this with combinations of React useState booleans was becoming unmaintainable.
We solved this by introducing xState, where we modelled everything using a state machine. In this talk I will explain how xState helped us solve this problem and hopefully inspire you to give it a try, in case you have a similar appropriate use case.

### Speaker Bio
- **Name:** Benjamin Komen
- **Mini-bio:** Full stack software developer, currently working on React Native mobile app
- **Would you like help with your presentation?** no that's ok
- **Social media link(s):** https://twitter.com/benjaminkomen
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?** yes

**Comment by ShMcK** [comment]
Hi @benjaminkomen, 

XState is pretty much my favorite topic, I would love if you could demonstrate its value to our audience.

Can I put you down for April 23rd?

**Comment by benjaminkomen** [comment]
Sounds good @ShMcK !

**Comment by bibschan** [comment]
hey @benjaminkomen I'm about to prepare the meetup slides and wondering if you'd like to have your picture on the speakers slide! If so, please send me a picture or link!

**Comment by benjaminkomen** [comment]
> hey @benjaminkomen I'm about to prepare the meetup slides and wondering if you'd like to have your picture on the speakers slide! If so, please send me a picture or link!

Sure, maybe just use: https://avatars.githubusercontent.com/u/12815582?v=4
