### ISSUE TITLE
Talk Proposal: Crash course in AI to calling functions

### ISSUE THREAD

**Issue by Sam-Hoult** [VanJS/meetup#89]
- **Draft Title:** Working with AI function calls to build your own AI driven services
- **Length:** (5 min lightning talk, or 10-20 min full presentation) Probably 10-20 mins to help cover the topics
- **Links:** (slides, article, notes) I just built an AI Budtender for my company on a Hackathon
- **Which dates, particularly Tue/Wed/Thu during the 2nd/3rd week of a month, are you likely available?** (e.g. "Most Thursdays with 4 weeks notice", "June or later", etc.) Not sure

Working with AI (ChatGPT or AWS Bedrock with Claude3) to call your own functions. Augment your existing services to be able to talk with an agent. Quick crash course on making AI customization. 

### Speaker Bio
- **Name:** Sam Hoult
- **Mini-bio:** (Tweet length is fine) CTO of Greenline POS and Chief Architect at BLAZE US
- **Would you like help with your presentation?** (feedback on notes, practice run) If it's useful, absolutely
- **Social media link(s):** (twitter, website, linkedin, etc.) https://www.linkedin.com/in/sam-hoult/
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?** Sure

**Comment by bibschan** [comment]
hey @Sam-Hoult this is a super interesting topic! Do you think we can put you down for May 21st? Also would you be okay with a 15min max talk?

**Comment by Sam-Hoult** [comment]
@bibschan Thanks for getting back to me, however unfortunately I'm leaving the lower mainland again so I won't be around to deliver this talk I'm so sorry! I hope to have something more interesting if/when I'm back in Vancouver
