### ISSUE TITLE
Talk Proposal: Intro to Open Source AI

### ISSUE THREAD

**Issue by kushalgoenka** [VanJS/meetup#90]
- **Draft Title:** Intro to Open Source AI
- **Length:** 20 min full presentation
- **Links:** The talk is an interactive web app (instead of PDF/slides)
- **Which dates, particularly Tue/Wed/Thu during the 2nd/3rd week of a month, are you likely available?** Available April 23.

### Short Summary

Short crash course to demystify Large Language Models (LLMs) & Embeddings, using everything open source.

Topics Covered: Natural Language Processing, Next Word Prediction, In-Context Learning, Fine-Tuning Models, Conversational AI, Structured Data from Unstructured, Tool Use, Embeddings, Retrieval Augmented Generation & more.

### Speaker Bio
- **Name:** Kushal Goenka
- **Mini-bio:** Freelance Software Developer
- **Would you like help with your presentation?** Nah, I got it, thanks!
- **Social media link(s):** http://kushalgoenka.com/
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?** Sure.

**Comment by bibschan** [comment]
hey @kushalgoenka thanks for opening up a PR with us! I see you suggested April 23rd for your talk, however we are scheduled full of speakers for this month -- would you be available on May 21st by any chance? Also, do you think you can keep the presentation to 15min or do you require 20? Thank you!

**Comment by kushalgoenka** [comment]
Hey @bibschan, thanks for the update. Sure, let’s do May 21st, and sure, I can keep it to 15 minutes.

**Comment by bibschan** [comment]
@kushalgoenka perfect! I'll earmark you for May 21st

**Comment by bibschan** [comment]
hey @kushalgoenka, you can get your free ticket using code `SPEAKER` here https://lu.ma/vanjs-may-2024

**Comment by bibschan** [comment]
@kushalgoenka would you be able to send me a picture of yourself that I can use for our introduction slides? thank you!

**Comment by bibschan** [comment]
thank you for talking yesterday @kushalgoenka!
