### ISSUE TITLE
Talk Proposal: The Observers APIs

### ISSUE THREAD

**Issue by sivcan** [VanJS/meetup#92]
- **Draft Title:** The Observers APIs.
- **Length:** 15 mins
- **Links:** -- N/A
- **Which dates, particularly Tue/Wed/Thu during the 2nd/3rd week of a month, are you likely available?** (e.g. "Most Thursdays with 4 weeks notice", "June or later", etc.): July/August preferably. Please message me on LinkedIn/something, I barely check my GitHub linked email for any email notifications on this issue. 

Summary:
We'll talk about a few observer APIs such as the Intersection Observer, Mutation Observer etc., which will really help new developers as well as experienced one to understand how to use them and why. 

### Speaker Bio
- **Name:** Sivcan Singh
- **Mini-bio:**  Building virtual machinery at Postman.
- **Would you like help with your presentation?** (feedback on notes, practice run)
- **Social media link(s):** https://linktr.ee/sivcan
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?** Yes

**Comment by bibschan** [comment]
hey @sivcan thanks for opening a new issue here! so happy to have you! I'll slot you in for July :)

**Comment by bibschan** [comment]
hey @sivcan feel free to grab your ticket https://lu.ma/kb271tfh using code `SPEAKER` 😄

**Comment by bibschan** [comment]
postponing to august as per sivcan's request

**Comment by bibschan** [comment]
moved to september as per sivcan's request

**Comment by bibschan** [comment]
thank you for speaking at VanJS @sivcan! I'd love to have you again
