### ISSUE TITLE
Talk Proposal: Back to the Future of MPA - Thinking about Astro in context of web  development history

### ISSUE THREAD

**Issue by Spice-Z** [VanJS/meetup#93]
- **Draft Title:** Back to the Future of MPA - Thinking about Astro in context of web  development history
- **Length:** (5 min lightning talk, or 10-20 min full presentation) 20min
- **Links:** (slides, article, notes) WIP
- **Which dates, particularly Tue/Wed/Thu during the 2nd/3rd week of a month, are you likely available?** I want to talk on [June's event ](https://github.com/VanJS/meetup/milestone/14)! 

Before SPAs became popular, MPAs were the norm.
Web servers ran on PHP, Ruby, or other languages, and used tools like templates, jQuery, and Gulp.
However, SPA libraries such as React, Angular, and Vue brought SPAs as the new standard.
Concurrently, TypeScript and Node.js were developed, enhancing the capabilities of developers. Numerous modern JavaScript frameworks like Next.js, Nuxt.js, and Gatsby now offer full-stack TypeScript development with options for SSR or SSG.
Currently, [Astro](https://astro.build/) advocates for a return to the MPA approach.
Why does Astro want to go back to MPAs?
I believe Astro's MPA approach is much more advanced than its predecessors.
I want to discuss why I favor Astro, contextualized by this history of web development.

### Speaker Bio
- **Name:** Yugo Ogura
- **Mini-bio:** Full Stack Engineer and Podcaster from Japan
- **Would you like help with your presentation?** (feedback on notes, practice run)
- **Social media link(s):** (twitter, website, linkedin, etc.) https://www.linkedin.com/in/yugo-spice-ogura/
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?** Yes

**Comment by bibschan** [comment]
hey there @Spice-Z thank you for opening an issue with us! Your talk proposal sounds super interesting, I'll put you down for June! Please use code `SPEAKER` to secure your ticket and let me know if you have any questions! :) https://lu.ma/vanjs-june-2024

**Comment by Spice-Z** [comment]
@bibschan 

Thank you!
I updated the Mini-bio!

**Comment by bibschan** [comment]
@Spice-Z perfect! would you be able to also send me a picture that I can use for our introduction slides?

**Comment by Spice-Z** [comment]
@bibschan 
Sure!
Can I use this picture?
[https://photos.app.goo.gl/AGCpDXGr7oA5K79y8](https://photos.app.goo.gl/AGCpDXGr7oA5K79y8)
