### ISSUE TITLE
Talk Proposal: JSR - new JavaScript package registry

### ISSUE THREAD

**Issue by kei95** [VanJS/meetup#94]
- **Draft Title:** 
JSR - new JavaScript package registry
- **Length:** (5 min lightning talk, or 10-20 min full presentation)
10 min
- **Links:** (slides, article, notes)
no link to my slides yet as I haven't worked on it, but here is the link to the official JSR: https://jsr.io
- **Which dates, particularly Tue/Wed/Thu during the 2nd/3rd week of a month, are you likely available?** (e.g. "Most Thursdays with 4 weeks notice", "June or later", etc.)
Any time

**short summary of your talk.**

As the ecosystem around JavaScript evolves, npm isn't just sufficient to take care of all JS packages anymore. Deno team has been working on the new JavaScript package registry (JSR) which is a superset of npm to adopt the modern JavaScript ecosystem which results in a better experience than npm for both package authors and users.

### Speaker Bio
- **Name:**  
Kei
- **Mini-bio:** (Tweet length is fine)
Kei is a TypeScript lover based in Vancouver. Currently working for a Healthtech company called Vivante Health as a Frontend Developer.
- **Would you like help with your presentation?** (feedback on notes, practice run)
No obligation but it would be great if I could have some!
- **Social media link(s):** (twitter, website, linkedin, etc.)
X: https://twitter.com/kei957
LinkedIn: https://www.linkedin.com/in/keisuke-yamashita-075164178/
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?**
Yes!

**Comment by bibschan** [comment]
hey there @kei95 thank you for opening another issue! Can I put you down for our June 18th event?

**Comment by kei95** [comment]
@bibschan Ya that day works for me. Thanks!

**Comment by bibschan** [comment]
perfect! feel free to grab your ticket using code `SPEAKER` here https://lu.ma/vanjs-june-2024

**Comment by bibschan** [comment]
@kei95 would you be able to send me a picture of yourself that I can use for our introduction slides? thank you!

**Comment by kei95** [comment]
@bibschan does my GitHub account's picture works for you?
