### ISSUE TITLE
Talk Proposal: Type-safety without trying much

### ISSUE THREAD

**Issue by kanta1207** [VanJS/meetup#95]
- **Draft Title:** Type-safety without trying much
- **Length:** Probably 5 min LT, but could be 10min. I want to try to minimise the content.
- **Links:** (slides, article, notes) Not yet ready. 
- **Which dates, particularly Tue/Wed/Thu during the 2nd/3rd week of a month, are you likely available?** (e.g. "Most Thursdays with 4 weeks notice", "June or later", etc.) If you can fit me in 18th June, it would be the best. Open for any arrangement tho!
- **Brief overview:** 

My whole talk will be like a quick step-by-step tour of how to do type-safe full stack development with minimum effort, using TypeScript, Next.js, Hono, Drizzle, and Zod. 

 "Type-safe" in here mainly means we can share the types between db, server, and client side code. 

"Minimum effort" means writing only minimum things for our application(DB schema, REST API server, and UI component). We don't need any extra things to achieve type-safety with this stack. 

Type-safety gives us pleasure, it's one of the biggest reason why we go for TypeScript full-stack development.
It would be even nicer if we can do it without trying much, because type-safety itself is not a goal.  

### Speaker Bio
- **Name:** Kanta Sakai
- **Mini-bio:** (Tweet length is fine) Full stack software developer expertise in TypeScript
- **Would you like help with your presentation?** (feedback on notes, practice run) No
- **Social media link(s):** (twitter, website, linkedin, etc.)
LinkedIn: https://www.linkedin.com/in/kanta-sakai/
Blog: https://www.kantasakai.dev/
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?** Yes

**Comment by bibschan** [comment]
hi @kanta1207, love the proposal! would you be available to speak at our next event on June 18th?

**Comment by kanta1207** [comment]
@bibschan Thank you! Yeah, June 18th works for me!

**Comment by bibschan** [comment]
Hey @kanta1207 feel free to grab your free ticket to the event, use code `SPEAKER` when grabbing a ticket :)
