### ISSUE TITLE
Talk Proposal: It's easier to be better in Vue

### ISSUE THREAD

**Issue by james2doyle** [VanJS/meetup#96]
- **Draft Title:** It's easier to be better in Vue
- **Length:** 10-20 min full presentation
- **Links:** A presentation based on this: https://gist.github.com/james2doyle/63a04ca610c98981a27e95ca93983992
- **Which dates, particularly Tue/Wed/Thu during the 2nd/3rd week of a month, are you likely available?** July talk, if there is one

Having used Vue since 2013 and React since 2018, I can make a strong argument that Vue is more stable, easier to learn, less likely to confuse you, includes more out-of-the-box features, and provides a better experience when building content-driven websites. This talk covers advanced topics such as hydration, state management, devtools, and details about the rendering cycle of each framework.

### Speaker Bio
- **Name:** James Doyle
- **Mini-bio:** James is the Principal Engineer at Engine Digital and has been building interactive websites and apps since 2010.
- **Would you like help with your presentation?** Notes would be helpful
- **Social media link(s):** @james2doyle everywhere, https://ohdoylerules.com/ is my site
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?** Yes

**Comment by bibschan** [comment]
hey @james2doyle thank you for opening an issue with us! Love this topic! I can slot you in for our July meetup -- we're thinking July 24th, would that work for you? Also I see you'd like to have your presentation reviewed, feel free to drop a link here when you're ready and we'll review :)

**Comment by james2doyle** [comment]
@bibschan Yep, that works for me. I will work on the slides and drop them when I have something worth reviewing

**Comment by bibschan** [comment]
hey @james2doyle feel free to grab your ticket https://lu.ma/kb271tfh using code SPEAKER 😄

**Comment by bibschan** [comment]
hey @james2doyle I'm preparing the slides for our meetup and was wondering if you have a picture of yourself that I could use for the intro? let me know!

**Comment by james2doyle** [comment]
@bibschan Yep here is one:

![IMG_20240629_211539](https://github.com/VanJS/meetup/assets/1425304/5c22b17f-8591-462b-8d3a-148da63c24b8)

**Comment by james2doyle** [comment]
Presentation slides. There are speaker notes with some links in them: https://www.figma.com/slides/xXormlgRwCbSNj1MWEjquZ/VanJS-2024-Vue-Presentation---James-Doyle%2C-Engine-Digital?node-id=1-26

**Comment by bibschan** [comment]
thanks for sharing the slides @james2doyle, they look dope! Great work! I do see you have 30 slides which makes me think your presentation might run over the 20 minutes we allocated -- are you able to time box it for 20min? let me know!

**Comment by james2doyle** [comment]
@bibschan Yep, no problem. I'm going to move quickly through the slides and get to the demos

**Comment by bibschan** [comment]
Great work delivering your presentation @james2doyle, I'm sold on Vue! On another note, I'll ping you on LinkedIn with the pictures as soon as I get my hands on them, let me know if you need anything else from us at this time! We'd love to have you again as a speaker or attendee 😄

**Comment by james2doyle** [comment]
I had a great time!

Slides: https://www.figma.com/deck/xXormlgRwCbSNj1MWEjquZ/VanJS-2024-Vue-Presentation---James-Doyle%2C-Engine-Digital?node-id=1-26&t=GgvGzoyfrOkTKB91-1&scaling=min-zoom&content-scaling=fixed&page-id=0%3A1

Here are the links to everything I showed:

[React demo with lag](https://reactplayground.vercel.app/#N4IgLgziBcBmCGAbCBTANCAbrK1QEsA7AExQA8A6AK1xHwFsAHAewCcwACAQUcY9lbN6HAOQUA9D0bUIZEQB1CDFuw4AlFPADGnAUNGtNOhUqZtOwDlsPwwKNc2acAvv0HCRNnQFpiQ8VqI+CiEYCaKWsyEEJyRofBEKKwcALwcfloArvQhYBQA5ihgAKKIKDmhAEIAngCSxAAUno5hAJQRUTEcgk6pVjZ2Dk4NcWAJhEnthD15hiRJDYoc6kZ51pp2peW5i4TLyxraeQDKYKz4OgCyzKRoS-uEmYiId3v7hzoU67YoWxVgDSkU2WU1aIAwUhkZBgdDMqg+YDQHEsmVQpx+SNR9hQsA4rj0wnkIC8YCJAG5FMpzBwYtUysQ3PoibT6d5ImYJqEIOTFB1opwpH0Gq1UgA+ZH3OJdIiMTKcNJYjSwBqPZ6tClvKWcADaOQgEHghSRqDAlxQ+sNKAAun0sei7IsQAAJFDPZgcADqbEQxAAhET1fdxOIOIRekdMkhENUOPArJ0wP7NQmOORGCEIPhMCgACoACyI+T6XFYrHg1QaAEYAKwAfQADI2G43gfsKLB8M8q63lhR6PBGA0GrWkfgRSlxWP7r2OyQh2OxRx8KkUmlLrY8xRBJk5+uwJuyyQhMKOAAqDiVxstkUAfhvojD+8LIg190MYEyrD2u32HAAPKK077H+eaVqKwB6gahTOH+4igYBby-n+Mpyt0OIpMAKFgK4mBIJkKAYZBlquFEtSELKYAYSeE40kUZoWoUDRYV8n5zHkuGIPhrSuOICG-ssf6MOBaYZlmuYFoQ+QweIQlAbBfEcIGhDOK+ExkConCkAgTwCrwGogM4zhAA)
[Vue demo with lag](https://play.vuejs.org/#eNp9Uu9r2zAQ/Veu+mJ7ZHay7FNnp3SjsA32g63QL4JgnEuiVpaEJLspxv97T3KTllJqsNHde/d879kDuzQm7ztk56x0jRXGg0PfmRVXojXaehjA4hZG2FrdQkLUhCuuGq2ch9btoAp4mnxHKTXcaCs3Z0nGVVHAvZAStJIPYDtFhwbPjoN4MKic6PF6L1TQuLS2fkg/zdfzebxJAejKt6SRLo5VW5s0Xc9AZFCt6HkiqU2aPjWhqir4Vft9bnVH/elYq41u0ww+wILU51kGFxeQKO3D+5MvXJXFZJ+MU+GxNbL2SBVAuV+shiGaHceyoCp2hTKdh/5jqzcoK84I5wyKCTRh4pXLMByCLYsX8mzGvKNQtmKX3zqt6EMMQYGzRrdGSLR/jBcUGmfnEJGA1RT2/c/Y87bD2bHf7LG5e6N/6w6hx9lfiw5tj5ydMF/bHfoJvvr/Gw90PoFkrpPEfgf8h07LLuw40b5S6rT2C17c9kf8nSiHa3d18CGXJ1Nh0cAcI58z+sW+vWP9ed1l/jnOcTVSiusebdCkAAnIl0s2PgKgteuv)
[Vue spinner](https://play.vuejs.org/#eNp9VMFO20AQ/ZWRVWQbHMchwMENqLTiQA8UlR4twcaeOAv2rrW7DqFR/r2z6zg4UuEQyzPz5u3bNxNvvOumiVcteqk307nijQGNpm2uMsHrRioDG1C4iCCXddMaLGALCyVr8KnJz0Qmcik0NVU8Rw2XFhychX2aFcVDXwlCuLzaAeMVq1qk5EF4ApM9X8NFT5cc0O0KOzYbvZMNohOYXiR9X6lYwVEYwvT3CDoCnwA8H/WAwKfGa6XYWzBUFsYLXlVBGNesCYLHCLgocO0INpkAUmlaJeBpqSsWfNkcXOoYAocm4otwm0STJDmKpvSbhPBlQyJhfOjCcce+LbD8CLBnnIQW9vQ1E9swfpZcBH7kh1TwQz+k7GzcDZXGSYHBuqmYQYoAZgVfQV4xrS8zr+GYL5kymXc1G1OhQ8xbY6SAbzmd/kKo3n5CPdzf3s3GHeBjsFNN6OuiABcMWmbjgRwKtXmr7Gvca+msbaTmhkuRAptrWdHo6FoAr7wwyxROk6RZu8QSebk0w8xcqgLVyE621SmcJ0ddmuUvpZKtKEa8ZiWmsBrNyc+g3wHrG4BRTOiFVHUKShpSGexg3WaSw2S8Hw7AvcyqgomGvJ3TXs3xL0cVJBEk8fm5fZ7Rc9J11UyVnDqmCmtI7AzdwJwPXuQZTbu54GX8rKWg/6ezI/PsAvMK1a/Gnkfupp1RtkZny9efLmdUi1Gfz5eYv/wn/6zXNpd59wo1qhVm3r5mSB3SQtjyzcMdrul9X6xl0VaE/qT4G924SGMH+06Ok+wBzqm9dV8ZLso/+mZtkGzcXcoKtcitw2cefW9+fHL1d7nT+Mz1kZ/k4uMKleUkA6kQT0+97T8l3Z/H)
[Vue options toggle](https://play.vuejs.org/#eNq1Vdty2zgM/RVUL04ztpS2O33QOt5NutntZdtkmr5VnQ4twTZriuSIlJyMx/9ekNQtl8n0pW8icAAegMDRPjrTOm5qjNJobvKKawsGba0XmUyOj6HAUpkUtoiaCd7gFGzFpOGWKzkFbFBaM4VmVqoCxRSMUO5scqWxgNwYOE4yyUutKgt7qHAFB1hVqoQJ3TnpXZfaJTStK07asyNGoJw+LXBzqVHCqctytGLC4PPOZdV6LbB1Hz2H00WLjhsmaiTjs/E5k/Mk1EpV0sFiqQWzSCeA+bK2Vkn4Oxc8355m0ZA8izyCMF/6JoCrnFCqtjNOCGBaI6taIEGNZpIaxFcECiQozVteIHxEWRMR8j9AI1W3uN6o3UPQPBkuD4STwDgcfpXZ/AM96Zl70uHy7hXusYWkv/pu0EMqv+N2JixWkp4HcsGMIddyPVsKlm/B4o2d7TbcYv80PpVeXKPA3AIrCs+GCVAh/bN54ma7BXaD9msFzpPRpNDR2FvhPtuJ2buQksvZjhd2k8LrCss/M3nIaOxmtChYzVhu3RJ5i0DWYGsJscNqpUSX5dzewkn80gAyg/cyuU0Z57Eq5GjjUjhpA/pmefeSvtaVqmWRgje3qKGTAZcroaoUvCVAaAjbcqNpZGnD5Yqv4x9GSZIOH5NFuSo1F1i1Xc2iNGRzPiaE2r33NlvVrgfBnm8w3z5i/2FunC2Lrio0WDX0xL3PsmqNNrgvrj8R95GTBq8WhH7C+RmNErXjGGDn1A+iPcJ5tu+8OHG5/mIubizS27RFOaIOefD4LCKZevNE6QPdV/EfPo46Sl0cqdwj8vuEagbV05XShrStwBWXeOVOR/7OfmNSOFeK5oOG9dCLpfGr4VctaOl+8Am0FOocPnncZ3Jp/4LJu/cf/v/46fJqEhstuD2aTCgUIIXJ2fmbfy7+/e/tHc9TMlvwpts6wZYoaO9XqqLtDhyAy44NaUC6xdvelUXd/qadIuwh7FE6qu5rQH87jLRhzqWu6X9xq502+dFbKpqz7g9GxocJRgo4KLRbmBGjxT2N9iV1J/dXHBL04mRUiZ0sDapEiTr4PAlNelR32p8sWQjUag/NGSfteEnC4/cfQDsFlOsUXvRiFLrtA1ZK2tmKlVyQYJRKKqohd/s+1pH4dasRY6nykTvk640lIVGiuBv04q5m0Kx/b+glqVIadFqC+NVJdPgJR/Pb+A==)
[Vue slider](https://play.vuejs.org/#eNqVVuFu2zYQfpWrgM1OJlty3QCr6mRbimbIfmzDVgwDqqJQpLPERCIFkpIdGH73HUlJlt2sTRMEIe+++3h3vDtq5/1S1/O2QS/yViqVrNagUDf1VcyD83PIsBIqgk2i08KH2vyDdZnkygctE66YZoJDLkVT+5CWiVIg7u4x1QrOg5izqhZSww4krn3HAntYS1HBhA6dxDzmqeBKA+MZbuHSAKfhWS/NmCQuc4TTTCaDqsS1Jun0DC6vnPW8TcoGSXa0u7yEEH6iv+hIPoMF9FSS5cVzuZbEtTzh+gEWQxhVkqMiuw8xB4i9QutaRUFQl0mKhSizeSqCH8NwuwzDILQ/wc3NTez5z8C/ujC/z8e/fn1z8y38Bn197fAx//iGSiAAwVMEXWB3Q2mRcIrQhzXLG4kgGg2bgtG9Hu5qg5CQKheM5zG3tz611j5MOW7+MUnzgQ63K5v0nXFvYBiy36PhaoBT/icct3pClzCpJbZURHuqilXgypcKlzYaKwpRI+0AVsXy6m2B6YP1VjQSVMkyVC/gVk8UvAwXFy9WAYEsOGOtq+TL2LM4GXsQ9ZIPg5MfY88akMn7oRV+NZ0APKmwtyZjneS0I15aHzGrgcKd268B2tlaSIJNbUH5wM4o/111mcvpcdEDPhLMKsbydqYKsTEaW7U2+6PD6DhW5RApmR6sITg4E5A3fXTBSXi9fJyou0ZraoBxPE4EP6clSx8IYhqW9N+X+s0qcMqj4AeuTOgx0UB1EIzy88kHdWui+58EDSlyqBNVf+QOJmkjJXI96Vrbps3ZwP7Yaoion1k99dVu15vQSID9/vM4R3l9IkV2EJkc5Z/l6GDZr1bBqMhpq/RjaZZzV7SupWrhLi6i8UlQ1iJ19X4A+eAWyqE3LNNFBDQP6u0Y16kLNP5FQLPiWD+jxKGcJdQXLdKk6aQlJi120lN3kjslykYbd2D0lJCiLCGcXyjARB0529FpcTjAHWufE0sv6iRl+jGCsDM0g6ILcQQ2BGZy9Jqe2JFYZ6i6qsgtTYb/nS7C8LuzJ1jHTo05T117mnU2ph0bjqN0R3yNKjQ0oxQsOtauM51plciccWKvKUfzC4mVNcqYokIio3WJ5mIB7hul2fpxRq+aJo8iUMSLszvUG0TeUXct46jXhJxtugq5o2ndgUw39+P99JQ8IT9eOi8ISyPc1rDne1rRyfTEzO+V4PRtYgliLxVVzUqUf9SmWKjRI0dtdFQ4YvOblWlJD0wvT83kf0J+r6hlI1r8KVGhbGkCDjpNeULqRKN+9/fvdN8jZSWypiT0F5R/oa1u8tHBrhuekdsjnPX21n4e0Sv5Xr3bUp5VH5Rx1CD33bNN30pvvxD6wd3l/JW1o3xSFj+1KA0nJZAU8+XC2/8HRsk/dg==)
[Vue search input](https://play.vuejs.org/#eNqlVm1v2zYQ/isXDajtwJbcZtsHz/bWBu2wNmiHtcMwTMOgSGeJNUVqJGXHMPzfdyQlW3LcbMC+JOa98e7h3T3aBy+rKtzUGMyCuU4VqwxoNHW1jEV0fQ0ZllLPYI1YJZxtcAxGJUIzw6TIlayrMeAGhdFj2ExKmSEfg0hKzEBzaaX2H1RKVvQ7lWVVG9JdR7FgZSWVgT0oXMEBVkqWMKBEBkfVR0xUWiT3HBttGJ1ENmcyTaXQBpj+UKGAhY01XCVc46hVGZnnHBv1cASLZWMdbhJeIwmvuudYzCMPAwFAB4NlxRODdAKY39fGSAE/pJyl60UcnILHwdLnNo+8kXf4dATLnUnyjpB8aZFsBCTq1LmZsBXF9RlRzNaGrNpM4Cvt7DEjwz1hWgsDh54tWVfL3wg10mUwx5LiGnww5ODMyXgeYbmEfeu/WCzgOXwPA4W65mYAs/anHsDhcDWPbEMco0c9WB4lKKQpmMgvZJSxTAwMrBjllYidMwvD8F/Dzzsv3yIZ9aGcRz2we0HoqM3OuTZPuLcuJROTLctMMYNvFZbfxeIQUx9MqJ9RTZLU2IZ3Eo7JBhuJ9z2NwQxklaTM7GAavtCAicazSLZ7u3GM9DEavxlMvQO1XpNlMA6MpgZesTz8rKWg6XQe9gHLinFUHyp7t46DmY9ldQnncvvWyYyqbepeTs2Sri/IP+sHK4uDn+mtUW0wDo46k6gcqVOs+vXH99Q9HSUNes3J+gnlL6glr22O3uwVtSKl3bFz2f7kRp264JN+/WCQIG2Ksolay4OzjwMa99snSj+lexN+7fwIUUKxvzAuLLnuGupsqP5C8qvk7xrVrlkyg8Fxw3BGfxbwh711D6XOaXZeqTpFuEOk6XEFtIq3SbpmCLdFIs5Vt0WdruG9VIrZoeu7oYE7di59V4sc3tRqR4pY/EkbO4It4xzuEeoqo97PqB3TAgwrEUyBTQkEiMhRtwW0Rd/5Qtrj0G9LB7EitJRwpYYrxqmph0NGA+b3Kf0IKaPQyDu5RXVLEzAchUykvM5QD92lfr2OCLXDEblm95zf2M3Hu4UcRW4KcqQKM6bQD6IpEkO1kj1q2yKTlUxr6gtgwlXbboD2vs0bq6cLXU0tWKoWsC2IH6yLvVsKGltiCVpTymap0CLpFoZNGLMZDJG7VJGH7s7hyD3Mo5C6kFsBSZ4w2kFAua6kwl/d01wK0m6BLxJQxjbt+itujoxDPxvhI77xPi2veMCXMIVnzxr0r2jzu2f1EPc5x5G3pXPybVmH4J051w6bnC16n5fDkqPB8+1uo3Y2e6em/gr/7xXN4fmXE2/YiPJ+0sdlPqVOd6z3v3KmRy5PxkxQN4PZVScUXS7ua4lEbjycxHUBRCfXU+gf7bdWW5F9L3IwSU6HmvdL56xbkw2q7BcF9ZEdi+5sxUHXcrbGXWNoh7mr7KFE3wytDX0ZdDHirIPQWepHtI7YtCBeJGog8qswI4l9a0/WtOEZke0LYuqWMEOLBAHpadodzrnbCZ+mbyIiou5vetTdidWydyfSRQJvgtoCLX3RT1vU78ObafUw6oZ9nE0lj7ncO9ps0mg/CIjI/tqgsuRIFEYMF95Mg8M/UV7XgA==)
[Vue multipage form](https://play.vuejs.org/#eNqlV3tv2zYQ/yqEhyGP2ZLTbH/Mc9K1XVC069Jh7j/DPAy0dLaYSJQmUnaCIN99Pz70sK2kSZYHbN4dj3e/e/B4N3hTFMG6osFkMFVRKQrNFOmqOJ/L8PiYxZTlasJ0yaUSWuRyyGhNUqshW4+yPKZ0yErikRZrGrIoz4pKU8yOw7kUWZGXmt2Bv2T3bFnmGTvASQc/Nbx3eSV1KUh5bhA2FGPTwVxGuVSaRVVZ4tCZpoKdGX2H4yNocUxJNzXn8IidnXelgzVPKwKnh3Z2xk7Za/xPerjfsZNaf1HS+oX6x9A/7tU/avUv8zL7hTQXqfLO3c0lY5JnNGEHB0OzoAzsZhVZkG6bNUcE3iEWDUEJOWGyShGcMGQbkaZsQYybSKWgZwsqjdhClDqJea3o3mA6DV0WIP5YaMqKlGvCirFpLNYsSrlSZ/PBpuRFATUDywIzOT1/jyRglWIc5+mEkDzWq2kInpcyzvrvWH1p0oqZXILavNIjIRutVsoca9AAWwHB0cl8gOQTS6y3EsMAvrXTnCcojZHQW1TQU1qRjM//zKvS6p6GnrIjJyQSmunbwpyukWk429tiPrACPhEleRpTCeKlI/raAKET3cDvKOnfSpSoknDb1rDX2Ce5YPPjST5YydaJerntxYWn9rtR73mOH9MQUXwsqK/scZQq6o8sgv58WHyhPATMr0TFmxRJu8MAa1apgqTa54DXdi3vgD/mQcBa/jZSXl9dZOybJSpnwaPrHinIKUop0iwWii9S2vWmEcsLW1C2z8AQ4PYp57GQqyAIpqHj9h8QuhP6bAy3OsE26wGspmE/vv8nz02nQ1Tjl9Rrs3cv3d90OP0RrDvsXghfluynX0l2FMPzsZl9uHwOKgXXmkoJwl/j0Y9/H4NkxXwjxi1BpYha+FQeCb7fKmaWjJkBPgh9W98uDZCBI+zgiQvqaVA+0ff6JnsSADHSuPWr3rrn2duW0Z8UnZ3PTopp2N599d0Ydi7Hvbu2kxHTRaU1KvznKBXRNfj1hAJDJnV3eOByfIvuMg2dgocV1iPVVxSaNL2E6I7CrqdT2Ab4TM5BwcfZ58tAoXfKlVjeHnbAHPpx5dURdE5D7HIjh1e11X+wVPo2JaaivLB9sIab2ckp4+XKDEBj/J6UlGGquZ/LAAUnkfEjP6xaSkp8TZ7iNreT7oTlBY9MTo+DV4oRV7SjyQytXT06dzr8PljgN/hhyXEBKDwBd5nSDQQYS0isEj1hP4zXiSVsRKwTsx4XTsKIjmJctrDUWBblaZXJjnan2u87GY+/tdv2j7qqlAb0I4yeGk5MmIKtNFqQ3hB5hbgHDLzAdTAcaIAMfFfBlcolHgn2HHPlZYVIqfxsrxM1H0ycBYaHSyzffLQ0XVYGaUePEoque+hX6sbQ5oPfS1JUrlGcDU8jloR2ZdgXM5NsHSaKskoh/QjzD1KAytjoxN5WMobZHTlr7Qf7HkFaflEXNwBG1U4ZQ43kvZWfD/AqefeI6625p8H3dh8QBYpbz5qep1b3rTTE3LwUkn4zLWf34WTGeWIRl5izydjjOhMKFfWrE6HsGyyXiC3jioklE5pt8A07XBOU+aZ+editeHN0zjs82j2DbzhUcHRPTPQ6L1iKB2DKNomIEve0gGOrFbLbCCg/CzQvNzf6fBL47h439sFidR66jyXpKDmcDxKtCzUJQySBdtsMXnAnXJ8GJyHi9NrV+Zmbo4ct7Alx9GwXChPSKKLCJw0KD02Nm1CFJoWBlIul2bfIY3Rv/1RqEod0ksdu9/uLL9sp5bMtys1pbWZjCgbiuAitDXjGZALn2wQ4OrKlY4DF32PPKz/ftZeND23dSvcHuxGbuT1mfLFAs9HOiOd31a1+PULTbUdW5EQ3RM5k8zO5pttWzL5cTCgyA2AjU1vyqFTT/Hul/M3ZGT23Wj1K5581IgsPUDWoqeB0PLj/DxFVUVQ=)
[Vue shopping filters](https://play.vuejs.org/#eNq1WAtvG7kR/iuELkCkVKuH7dzVqmL0mqTAHS4P1NeixelQULuUlskuuSC5khXD/73fkNzVSlbsC+DagLCcF2eGw+HM3PZ+rKrRpha9WW9uUyMrx6xwdXW1UOMXL1gmSm1nTGyEcnbINkmpM1EMmShECRAzYjVkqS6r2omMvRgvlCwrbRy7DSit3ulaEe6OrYwu2XPs9byl+mhkKtU6okbjuCaFQAQVxszlglnHnWB65RcrbcqFSrWyjlXc8NKyV7RZ//Zu8JeWJSo4ZJxwwgiVCuZ0K4FJ5b/ffHjXCMPy74QJ0lRdFIOoA6+dLrmTKS+KHXyyhE0pbHI5V58tiSWRI61eA7AWjUCtSF6AQWrfe3HAXl2x24VicBsREecb7jgIlNgy4qBlIB45btbCjYgIyjQ8IPwXL2pBln9YfhIpKODBt8oZKWy/ETmCBA8YeF4YYgQO19sdPQfVtzkPIGKzLK0NnIUo8D6XljgD8WhDewY9w/Zw9x25qD3lfn9vnlyxfnRp4BwEuFeEPMl0bRickxXCMG6JYStYyTOBQ0ujJ4m+68f+LQs+mSHESONZc25Rvbu7AWPEB83uYPd8HMIaAY2FE2VVwDCs5j4M0oJb+2rRK5MLtirEzaJHpw9AlIr1X4MugB0o8iwc56IHWYzNM7lhipdEZiVChBuwNtJJshefpLpga14lF5Evcn6d8KwlBGl+3lI6ceOSYg3s3Dqj1frqdaFdTrfp110lLOwO4Pk4P99L+OpmnW1AVvClKMi/ZE4ujbMda3Juk99maS7SzyL7fbbSyiVLXWQHIiBEKqQF5qANmDz5UpODZdaV2jitWftjBGCK7/GhQFtxdXXtCWEeLToqj73OXzcC+eb/YESU2hoR148bQYTfagSIn96GRmg0oVk+ZsFHonvUgPkYAdcEevf7qYL+Wn550lgvkZiePEqi0CZI4vLRGCG6bw2RUmSypqz1pBa0UqMJ7foxG955wm81oqAM/9Q2NEKjCc3yMQt+IbonjPOS3yTbZBpem6NgfDjUY3H0lWBvSqnGhr0Wna+uNnjx9m9QZQSKO9oTmJ+vP7wfYROIk6tdP7z+Q0YV0ZCd0Ys3H4PhQPh8TM+p/+i8sVhatyvo88WQzWZLASpBX3zl8Or7giBJ3BbHaTJhEriZrEhuZmyC6uI0cneAdIYrS/sdMe3hh/RGU2VzALKfxfaI24MOGS2KFr/J9BgGug4MkUJUhwCQdABSpXnyRWtUL11ZRhdFYhUSIHk/dUpYFN+V0TeylG63J10bnklUHwmVfUmlrXRSq66wlmIj+cMETp/Ew+VS8eJAQUROLrLkizC6C1d1KaBuspLr2sCz9zHx5E4yGZ4e702Rl0iFWvUeVK9WACdbmbkcp1PdnMbjXmkzY9+tVqsjgogx62X/5SWbnk/Y2cX3bMwmo5fUPpyQZXOe6S02w/93E/wdkT2AfxQV1BHZSZJlUUPTztrIdR6DYg9FS4BQtweuwuHufGh2gXkt2uDfQ6XaCHPAbLmrzRGVFZXkXUBmNKI0mtdRkaefPeqe7i3ipBEt+pQ1LfKkWS32tH0t+r6hLUpTeLqDK9riTnljjzx2C6nPpUosypJT8ILvdH2gRIOp8HMS4ROoR6CjGVGf4rNmiXdJ4tZMjSgb3DL5cxeJvOnQuM7Y2Z7Gv0GeJpMWaRpGEyhi8+QiSsgFHRPEd3jbpyvugVW4huejl3uqcATJ5aST3ZtjuZxkYu1N9Nk59m9Nou5vuOkf5/QBpg73wbvBgAWhe6awBoJy97/38JDdI/w/R3AS5EOqyxASfYPpsoR0P6BM0XjTF63eVL/KpEE/7hMaEHWpIqkvawMdPnHfuz7zHWEH2TnUWAfEHajyCbE1HU3PogTGCqlE0h7Z6IeO6LZY6kjYRsoffLbxB48Ka7H4bbFoqqzF4ncsWuYZCPoNLjbyp0VReUIvfm/YcxYxjEdh9MlqhQGT50JhhnGRRM//oSI3oddAKx/KkEUPFa/e/uxhztRi2MD9zifgnyzquxk+PtJow2xQ0bW4MCcI6LfX7+HHDhJzrLoA9QPIfwiLAyQdA9nfaj+q6NB5bX/yoyw8BL/atzdOKNsYRYr6QYSnX/Qw1Hr9gOl7dc9HF80AA17szMRODOkOx23tJO5w2haHZRBE4xuabj3/fjJ5TlG8H0JxRxVZmEL9pFwxel+XS2Fo4sFdf9ETKvnnNYzHXjEl4Vj8sCjdEbj5JvjrH98QCClClnV5LddKrjA9U+6NXEuHzH/OaDaDQdBWYhBUVxkNm7a5CEO5oGmY54ThC8ZQHSN+8b3Cq9bc47ETKlYrYEPfUzfTpyt2eXnZDqEMHGgUdH0GKPvToucvEnz+kIg5m04m90Uk7BngXRE04sp1hZllGFo2zmEYd1HCk7ixa1TU5GE/Youy2oPwIz/4vbv9IwOttolqK3y8B+hq4uyABFG/01T5e0/6gn7fz9zvWfyzcK9f+UP99R9twkPrFufLHXVjM4fE323eGmwYYMRFKVXs4xB39OXPpN28fZcOGr3Tjdu+q+n4F3fxvygh6H7jIuKSjs6nvbv/ARKWj3Q=)
[Vue cart with standalone state](https://play.vuejs.org/#eNqlVwtvG0UQ/iuDKcQp9jlpCqImiSiBSkWiRTQgqrpC57uxve1597jdc+xG+e98s3svO05oQZalu3nv7Dy+u+49zfNoVXJv3Du1SaFyR5ZdmZ9P9OjhQ0p5aeyYXBFrq5wyekC8Yu3sgFbDpUk5G1DBceLUigeUmGVeOk7p4Wii1TI3haNr8Gd0Q7PCLOkAng5alrIvc4ZJZ+bzjMOzss/1RVy4AcVpemnCoyjLU20mGlkXO46cba0Jv2HLixwL7MRo6ygvTFomztIZvZlogu90TMdwrVzGYzq4MCaj546XBwP62208Ly9UAt630ZMnN4NG6VGr9KrMuaDLhdLz22pPosde7e1En45CapFUvMBJniF6vBGdpmpFSRZbezbpXRVxDouTnmcF5vnptHTOaPo+yVTyHlJttiD4h+Irf/TTUZA7Px2JVmXgsrm4igKaT9RqqGawFW6gfzjpiX1jedd+rQW9xcn5a1MWlTe8NRZ9umuXo1s+/TEaYTnwajgzBVxVt0JKNxeESMbvedMyhVAn6M1BRUS6rylVNp5mjDupi6ZfsQ/p5u128N00q2U8Z7AfPHjQTZaX2012U4SN6S270LB5rNt07sQB4evr+myRrwy6uaHvCdS6qBvhCBUELqoFJvc64czy+dM0RcdQ4q9hR7SpgvZuOtXQPNdPp6NOMeLVuk3GZBOTcwpKlYxrUVkqPbxSqVuM6ZuCl99N9M1ERwhJOy6G1QTwlIzjFVeUoNuOjzHFWUZH0SNLHFvesSIZ6drAKVt9VMyymkQS8Ov+8JujfH0IE0QmjxMl7XdUWaw6KaijTnBGcGcZr738gtV84cb09dFq4QnCGaaqYEQtUSYmK5fas96V1qnZZog54hDmmJDyhIdTdlfMIiL+6kL2/qo0PTpCfFvuWsrtkO6MoGM+qis++GlPHX1dCfrSDtza6XHjdBon7+eFKXWKw2SmGNPnJycnd8QTZ2quhwr1gfmf+PvZn44Or7J6tYBaCAgFKiWFWuoNeg6FpWdqHr2zRmPh+DAnPdkaKuPiZS4nxwAYhwMID9Virn72NFeUUmCBniw4eb+H/s6uhTbp/Vqw5WKFNm94Li7mjHEi7J9eveA1nhsmdlmZQfoe5m9scScSYxD7AYlE2B05H+1zv46wEi7tT2ukyNaHkkBFMuySSQ/r6eKeo7fhnkSPvR4yiizWmw8J7KzYqt229yx2+Ijilmum71Be5Baxw/jQNGVaxlrlpTRUiiKQ6ss2FGtMmELN5+igMk/BtDKiZfjLZRktCGCiee3dhwXrw8J2rZ31r1GfjEKexRhawAYYV2PS2Fav2PUxoKVzd2yEbQQj4J+dB5ORWLkl2e6oPdIgfXaPbjPSRVUK3Kv7vActCTWCVGAKHWn0hjEMQW8lK2/hZnE/O54wJ82Kn1Vz/l53QFLseMuj38e4LPa5IzUjJSkiTGy3ERlQ+h0TVn1gOqVj+vLLTniHdUVtRewvpS6qPfcQ1thWxB1Pi9jWkfoSmxfx1AcaisDM/Es9E31F1sfY8VTvwC1Pb6Io6nhbxVnJtn/4NpopnfZRWCpF+YgkHs7OzpAXXkYq9eFsmRf9S+PirKmSu2xLLqJlnPdbCAHp7cX9sHnHova3FBWMd+73MW3KTFAxrBYbr1uR6KtAG9BRN76UZzHYIWPo6hqw7sPhKD50XshthtbyzRhrg5wWNMP8aDta2MJVcGyugKoy7KrPWsTtjQhk7xZmaE6fp70Au7oq7N/YYdQjl9LGz7XLohflcsrFM8/qT3qsh7+/wkDESPJzX8ZkUhYF62Qj5PpZ6BdPfwS0u0FScMBq8SF4f5QpY87gnBiS+MrQDGU5lRRRDVjqsFa/CB8xBZSC7YZRNqa+fJlck7/fqlg4ixzm+kVYXNIE9Ymi8NT30od+PIex978NhRX4UeDfd8f9yP8BL5XrH/jBcCDY8s/9qN8r28w4Gt1i7MPebUN0wO1WcB7zpLcgdRfc+o8iD193ILXS+Cgkt8nl40L7gsF1Vp+PbSDSVKADZ4J2jKfRLn6vaqGjsqcvEeO/gvrt8u+C9Tah9wPou9Ljgfq5b6VxBc4b8F4H3zSbfHYhWC/1ydjcX1co+tw04HrqIYqAL6IPQ4xLXgN2+ldncgG8FRbMsceAUQAPA5hvUOvJPah1D4CczWaBZdZDu4hTczWmx/na/4+hR8V8GvePBv4XPQ5w/RPRb8juFrYGqP3iDlMfg9dDSXYNVokRd84vjDBOgMEUwnmEJPlvi//qsMbBmPR/rbgQTIhJD2AXnRz1bv4BUcXmsA==)
