### ISSUE TITLE
Talk Proposal: 5 hacks to speed up your nextjs app

### ISSUE THREAD

**Issue by YourTechBud** [VanJS/meetup#97]
- **Draft Title:** 5 hacks to speed up your nextjs app
- **Length:** (5 min lightning talk, or 10-20 min full presentation) As much time as you can gimme.
- **Links:** (slides, article, notes) Not prepared yet.
- **Which dates, particularly Tue/Wed/Thu during the 2nd/3rd week of a month, are you likely available?** (e.g. "Most Thursdays with 4 weeks notice", "June or later", etc.). August

There are tons of blogs and videos out there which show you different ways you can optimise your nextjs app. This is probably one of those. 

I've curated a list of 5 optimizations which I've found sitting in my codebase staring at me pleading to be fixed. They range from changing a few lines of code to minor architectural modifications. Nothing the VanJS community can't handle ;).

All these are based on my personal observations working on small scale hobby projects as well as enterprise codebases in production.

### Speaker Bio
- **Name:** Noorain _YourTechBud_
- **Mini-bio:** (Tweet length is fine) Die-hard engineer turned product manager with an on-and-off relationship with React.
- **Would you like help with your presentation?** (feedback on notes, practice run): It would be helpful. Sure.
- **Social media link(s):** (twitter, website, linkedin, etc.): [LinkedIn](https://www.linkedin.com/in/noorain-panjwani), [YouTube](https://youtube.com/@yourtechbudcodes)
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?** Do I even have an option? Ofcourse I do!

**Comment by bibschan** [comment]
thank you for speaking at VanJS @YourTechBud! See you soon for your next talk!
