### ISSUE TITLE
Talk Proposal: NextJS, basics and benefits

### ISSUE THREAD

**Issue by umerkha2007** [VanJS/meetup#98]
- **Draft Title:** NextJS - Basics and Benefits
- **Length:** 10-20 min full presentation
- **Links:**  Slides: https://docs.google.com/presentation/d/1m7OBSEqGuVu3jgOgVBIqtdOe7lBLJEoek0Qsx30idgE/edit#slide=id.g2cce02bef39_0_110
- **Which dates, particularly Tue/Wed/Thu during the 2nd/3rd week of a month, are you likely available?** (e.g. "Most Thursdays with 4 weeks notice", "June or later", etc.): 27th July VanJS Event

Please replace this sentence with a short summary of your talk.

This lecture/talk is going to be about Introduction to NextJS. What benefits it has, when should we use it, when should we NOT use it, some sample code of the features of NextJS etc.

### Speaker Bio
- **Name:** Umer Khalid
- **Mini-bio:** Worked in the industry for 7 years, now working at BrainStation
- **Would you like help with your presentation?** Yes
- **Social media link(s):** https://www.linkedin.com/in/umerkhalid1/
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?** Yes

**Comment by bibschan** [comment]
hey @umerkha2007 thank you for opening an issue with us! I see you suggested July 27th for this talk but we are not accepting any more talks there. Would you be willing to speak in September? (we just closed August as well unfortunately)

**Comment by umerkha2007** [comment]
Hey @bibschan,
Thanks for checking my ticket. I would love to do the lecture on the next available slot. So, July 24th it is!

Thanks again 👍

**Comment by bibschan** [comment]
@umerkha2007 make sure you secure your free ticket through luma using code `SPEAKER` 😄

**Comment by bibschan** [comment]
hey @umerkha2007 I'm preparing the slides for our meetup and was wondering if you have a picture of yourself that I could use for the intro? let me know!

**Comment by umerkha2007** [comment]
Hey @bibschan sorry for the late response. You can use this photo:
![1711398254297](https://github.com/VanJS/meetup/assets/87485284/ee59b0d6-382d-4569-89f1-6a9903da7ac6)

**Comment by bibschan** [comment]
@umerkha2007 let me know how you'd like me to introduce you to the crowd before you talk! Your Mini-bio is `Worked in the industry for 7 years, now working at BrainStation` so I could use that, but lmk if you prefer anything else :)

**Comment by umerkha2007** [comment]
Hey @bibschan, the Mini-bio you suggested works for me.

**Comment by bibschan** [comment]
Thank you for speaking at VanJS and sharing with the community @umerkha2007! I'll send you the event pictures as soon as I get my hands on them, let me know if you need anything else from us at this time. See you again next month! 😄
