### ISSUE TITLE
Talk Proposal: Building a Full Stack Website in 30 Minutes Using AI & Vercel

### ISSUE THREAD

**Issue by mappmechanic** [VanJS/meetup#99]
- **Draft Title:** Building a Full Stack Website in 30 Minutes Using AI & Vercel 
- **Length:** (20-30 min full presentation/workshop)
- **Links:** Code Example: https://github.com/mappmechanic/rahatkhanna.me
- **Which dates:** Most Wednesday or Thursdays in August or September

This session will demonstrate how to build a full stack website from scratch in just 30 minutes using AI and Vercel. Utilizing ChatGPT and Vercel AI tools, I will guide attendees through the process of creating and deploying a website, connected to Google Cloud DB or other APIs. The session will be hands-on, focusing on practical implementation with minimal slides.

### Speaker Bio
- **Name:** Rahat Khanna
- **Mini-bio:** Senior Software Engineer at Apple, with extensive experience in web and app development. Passionate about leveraging AI to enhance productivity and streamline development processes.
- **Would you like help with your presentation?** Practice run
- **Social media link(s):** https://linkedin.com/in/rahatkh
- **Do you agree to the [VanJS Code of Conduct](https://github.com/VanJS/meetup/blob/master/CONDUCT.md)?** Yes

**Comment by bibschan** [comment]
@mappmechanic hey Rahat! I finally got solid dates for our August event, does the 28th work for you? Let me know :)

**Comment by mappmechanic** [comment]
Yes 28th August works for me, sounds good

**Comment by bibschan** [comment]
Perfect! Please secure your ticket using code SPEAKER here https://lu.ma/kb271tfh @mappmechanic

**Comment by mappmechanic** [comment]
This link is not for the 28th August one ?

**Comment by bibschan** [comment]
> This link is not for the 28th August one ?

Omg I’m so sorry, I got confused for a sec… This is it: https://lu.ma/gykjonp2

**Comment by bibschan** [comment]
@mappmechanic would you be able to send me your headshot for our website and event slides? thanks!

**Comment by bibschan** [comment]
thank you for speaking at VanJS @mappmechanic!
